### ISSUE TITLE
No JS kernel listed -> IPython 3.0.0, OS X 10.10.2

### ISSUE THREAD

**Issue by JulianTonti** [n-riesco/ijavascript#10]
- Installed with: <code>sudo npm install -g ijavascript</code>  --> no problems

- Launched with: <code>ijs</code> --> fires up IPython / Jupyter, but there is no JavaScript kernel listed in the <code>New -> Notebooks</code> dropdown menu.

![image](https://cloud.githubusercontent.com/assets/120087/6840454/5031ff48-d3b3-11e4-9c69-90386ae9d19f.png)

- edited <code>/usr/local/lib/node_modules/ijavascript/bin/ijavascript.js</code> and added <code>console.log(config);</code> just before the spawn() -->

```javascript
{
  nodePath: 'node',
  ijsPath: '/usr/local/lib/node_modules/ijavascript/bin/ijavascript.js',
  rootPath: '/usr/local/lib/node_modules/ijavascript',
  kernelPath: '/usr/local/lib/node_modules/ijavascript/lib/kernel.js',
  kernelArgs: [
    'node',
    '/usr/local/lib/node_modules/ijavascript/lib/kernel.js',
    '/Users/julian',
    '{connection_file}' // <-- should this be a path to a connection.js file?
  ],
  ipythonArgs: [
    'notebook',
    '--KernelManager.kernel_cmd=[\'node\', \'/usr/local/lib/node_modules/ijavascript/lib/kernel.js\', \'/Users/julian\', \'{connection_file}\']'
  ],
  cwd: '/Users/julian'
}
```

- poked around in the various .js files to look for something like this...

```javascript
{
  "control_port": 50160,
  "shell_port": 57503,
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "stdin_port": 52597,
  "hb_port": 42540,
  "ip": "127.0.0.1",
  "iopub_port": 40885,
  "key": "a0436f6c-1916-498b-8eb9-e81ab9368e84"
}
```
(from [http://ipython.org/ipython-doc/dev/development/kernels.html](http://ipython.org/ipython-doc/dev/development/kernels.html) )

... but didn't find anything. Any suggestions?

<b>[edit] fixed it by creating a kernel.json file as follows:</b>

```bash
cd ~/.ipython/kernels
mkdir javascript
subl ./javascript/kernel.json
```
```javascript
{
  "display_name": "JavaScript",
  "argv": [
    "node",
    "/usr/local/lib/node_modules/ijavascript/lib/kernel.js",
    "/Users/julian",
    "{connection_file}"
  ],
  "language": "javascript"
}
```
- seems like the <code>--KernelManager.kernel_cmd</code> parameter is not being picked up

**Comment by n-riesco** [comment]
`--KernelManager.kernel_cmd` has been deprecated in IPython 3.0.0. This means that the Javascript kernel appears listed as `Python 2`. I will look for a fix today.

**Comment by n-riesco** [comment]
Commit ba154a67bad312c15f02e2db670f9f8f68df8913 fixes this issue. I haven't released this commit to `npm` yet. To install it in your machine, you'll have to clone the git repository:

```
git clone https://github.com/n-riesco/ijavascript.git
npm install -g ./ijavascript
```

**Comment by JulianTonti** [comment]
Thanks Nicolas. Great work BTW, I poked around in your JS code and found it to be pleasantly clean and well structured. I approve!
