### ISSUE TITLE
There is no obvious way to customize jupyter console to use vi editing mode...

### ISSUE THREAD

**Issue by mario-grgic** [n-riesco/ijavascript#113]
IPython jupyter console has concept of profiles where you can customize the IPython color schemes, and slew of other settings, including most importantly vi-editing mode for the command line. 

Is there such capability for javascript kernel as well?

**Comment by mario-grgic** [comment]
Ok, apparently you can run ```jupyter console --generate-config``` and then get jupyter config file in ```~/.jupyter/jupyter_console_config.py``` that you can then customize.

Sorry about the confusion.

**Comment by n-riesco** [comment]
It's also possible to use `ijsconsole` to pass command flags onto `jupyter console`.

For example: `ijsconsole --ZMQTerminalInteractiveShell.editing_mode=vi`

If you need to preload any javascript libraries, `ijsconsole` accepts the flag `--ijs-startup-script=path/to/file/or/folder`.
