### ISSUE TITLE
Proposal: Improve $$async$$ and $$done$$ api with promises

### ISSUE THREAD

**Issue by thalesmello** [n-riesco/ijavascript#115]
Every time the returned object is a promise, I propose we wait the promise to complete before fetching the result by default.

For example, instead of:

```js
$$async$$ = true
var { promisify } = require('util')
var delay = promisify(setTimeout)

delay(1000)
  .then(() => $$svg$$ = "<svg><circle cx='30px' cy='30px' r='20px'/></svg>")
  .then(() => $$done$$())
```

We could have:

```js
var { promisify } = require('util')
var delay = promisify(setTimeout)

delay(1000)
  .then(() => $$svg$$ = "<svg><circle cx='30px' cy='30px' r='20px'/></svg>")
```

The idea is that we would have it await by default.

What do you think?

**Comment by n-riesco** [comment]
I'm tracking this issue in the repository for the NEL package. See [this issue](https://github.com/n-riesco/nel/issues/6).

I'm about to publish an update that implements [display_data](https://github.com/n-riesco/ijavascript/issues/95). I'll work on Promises in outputs next.

I'm closing this issue. Please, continue the discussion in [the NEL issue](https://github.com/n-riesco/nel/issues/6).
