### ISSUE TITLE
Dependencies on macOS

### ISSUE THREAD

**Issue by lukejanicke** [n-riesco/ijavascript#119]
Could someone clarify whether `pkg-config` and `zeromq` (via `brew`) and `pyzmq` (via `pip`) are actually dependencies of `ijavascript`. The README isn’t explicit on this and I would prefer to know before installing them or finding out by trial and error.

**Comment by rgbkrk** [comment]
ijavascript should be using prebuilt binaries on mac, so it _should_ just work

**Comment by n-riesco** [comment]
What @rgbkrk said plus the dependency on `jupyter`.

`jupyter` could be installed using `pip` but there are other ways (see [here](https://jupyter.org/install.html)).
