### ISSUE TITLE
creating and manipulating dom objects

### ISSUE THREAD

**Issue by thwee-alchemist** [n-riesco/ijavascript#120]
I'm trying to write about my 3D graph visualization library, [fourd.js](https://github.com/thwee-alchemist/fourd.js), and was wondering whether there was a way to access the dom elements as they are created in your documentation. For example, would jquery work, or three.js?

**Comment by n-riesco** [comment]
The answer depends on the CSP policies of the frontend you're using (I haven't tested this recently, but most of them don't allow JS injection).

See [this answer in stackoverflow](https://stackoverflow.com/questions/43488464/how-to-output-svg-in-a-jupyter-notebook-using-jsdom-d3-and-ijavascript/43514776#43514776) for an example using JSDom and D3.
