### ISSUE TITLE
Add flag --hide-execution-result

### ISSUE THREAD

**Issue by JocelynDelalande** [n-riesco/ijavascript#121]
See that example:

![image](https://user-images.githubusercontent.com/429633/31852051-546d2300-b671-11e7-808b-200b8eca1307.png)

I understand that ijavascript outputs the value of the latest affected variable (so displaying *11*, which is the value of `i`).

But in the context of teaching programming basics, this is very confusing (*"why does it counts till 11 instead of 10 ?"* ).

So…

## Short-term question

Is there a way to disable this behavior ?

## Long-term question

Is this behavior desirable at all ?

 FYI, ipython python core does not have this behavior:

![image](https://user-images.githubusercontent.com/429633/31852093-14eb205a-b672-11e7-8c1d-a05cbc212a8e.png)

Thanks by advance :-)

**Comment by rgbkrk** [comment]
This is [part of JavaScript itself](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-block-runtime-semantics-evaluation). If you try the same in the `node` console or in devtools for Chrome or Firefox, you'll get the same:

<img width="598" alt="screen shot 2017-10-21 at 8 40 44 am" src="https://user-images.githubusercontent.com/836375/31853365-fa753354-b63b-11e7-8757-1be29026915b.png">

REPLs show the last result of the code. What's peculiar is that **JavaScript while loops and blocks have a result**. The result of a block is the result of the last statement in the block (`{1; 2}` --> `2`). The result of a while statement is the result of the last iteration of the statement.

**Comment by rgbkrk** [comment]
In case you were curious, the same applies to `for` loops too:

<img width="598" alt="screen shot 2017-10-21 at 8 50 35 am" src="https://user-images.githubusercontent.com/836375/31853436-ec3ee478-b63c-11e7-9860-a5bd98999737.png">

**Comment by JocelynDelalande** [comment]
@rgbkrk ok, very interesting.  

So my only (reasonable) way here seems to be disabling the display of all execution results, I have to search on that. 

I left this issue open for a few days in case someone comes with something better.

**Comment by n-riesco** [comment]
@JocelynDelalande to avoid this JS behaviour, you could rewrite your code like this:

```js
var i = 0;
while(i < 10) {
    console.log(i++);
}
```

**Comment by JocelynDelalande** [comment]
Nicolas Riesco <notifications@github.com> wrote:
> @JocelynDelalande to avoid this JS behaviour, you could rewrite
> your code like this:
> 
> ```js
> var i = 0;
> while(i < 10) {
>     console.log(i++);
> }
> ```

@n-riesco Thanks, but for a gentle introduction to algorithmics,
this is pretty hardcore stuff :-).

**Comment by n-riesco** [comment]
@JocelynDelalande Oh, I see. In that case, I'd use a `for`-loop:

```js
for(var i = 0; i < 10; i++) {
    console.log(i);
}
```

**Comment by JocelynDelalande** [comment]
@n-riesco yes, but in this very case, my point si to show/experiment the `while` loop.

I'm trying to adapt the tools for the teaching, not the teaching to to the tools :-)

@n-riesco any idea/lead on how to disable the display of the latest evaluated expression in ijavascript notebooks ?

**Comment by n-riesco** [comment]
> ~~@n-riesco yes, but in this very case, my point si to show/experiment the while loop.~~
>
> ~~I'm trying to adapt the tools for the teaching, not the teaching to to the tools :-)~~
>
> @n-riesco any idea/lead on how to disable the display of the latest evaluated expression in ijavascript notebooks ?

The idea behind the examples I've given above is to ensure the last statement returns `undefined` (by default `ijsinstall` installs the IJavascript kernel with the flag `--hide-undefined`).

I could implement a flag to hide execution results (e.g. `--hide-execution-result`). I don't see any harm with such an option.

Alternatively, one could develop an nbextension to hide execution results (like https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/hide_input_all). This approach would work regardless the kernel.

**Comment by JocelynDelalande** [comment]
@n-riesco great, thanks :-)

**Comment by n-riesco** [comment]
@JocelynDelalande I haven't published a new release in `npm` yet. I wanted to update IJavascript's documentation before making a new release. But, if you're a going to use this feature straight away, I could make a release today.

**Comment by JocelynDelalande** [comment]
I'm fine, I'll maybe use it in several months :-)
