### ISSUE TITLE
error on installation in ubuntu 16.04

### ISSUE THREAD

**Issue by jyapujuju** [n-riesco/ijavascript#127]
`sudo apt-get install nodejs-legacy npm ipython ipython-notebook
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs-legacy : Depends: nodejs (>= 0.6.19~dfsg1-3~) but it is not going to be installed
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

`sudo npm install -g ijavascript
prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/zeromq-v4.6.0-node-v57-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/aato/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-node-v57-linux-x64.tar.gz
prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/download/v4.6.0/zeromq-v4.6.0-node-v57-linux-x64.tar.gz
prebuild-install http 200 https://github.com/zeromq/zeromq.js/releases/download/v4.6.0/zeromq-v4.6.0-node-v57-linux-x64.tar.gz
prebuild-install info downloading to @ /home/aato/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-node-v57-linux-x64.tar.gz.16039-f277e0e88f7c8.tmp
prebuild-install info renaming to @ /home/aato/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-node-v57-linux-x64.tar.gz
prebuild-install info unpacking @ /home/aato/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-node-v57-linux-x64.tar.gz
prebuild-install WARN install EACCES: permission denied, mkdir '/usr/lib/node_modules/ijavascript/node_modules/zeromq/build'

fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ijavascript/node_modules/zeromq/zmq'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.<anonymous> (/usr/lib/node_modules/ijavascript/node_modules/zeromq/scripts/preinstall.js:89:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`

**Comment by n-riesco** [comment]
How did you install `node` and `npm`?

This portion of the error messages suggest the versions of `node` and `npm` provided in the Ubuntu repositories couldn't be installed:
```
The following packages have unmet dependencies:
nodejs-legacy : Depends: nodejs (>= 0.6.19dfsg1-3) but it is not going to be installed
npm : Depends: nodejs but it is not going to be installed
[...]
```

Could you run `npm --versions` and post the output here, please?

**Comment by jyapujuju** [comment]
5.5.1

**Comment by n-riesco** [comment]
I'm going to assume you've installed `node@9.2.0` and `npm@5.5.1` (unfortunately, these versions are affected by https://github.com/nodejs/node/issues/16649 and https://github.com/npm/npm/issues/19019 ).

See my comment [here](https://github.com/n-riesco/ijavascript/issues/124#issuecomment-345625577) for a workaround.

I'm closing this issue in favour of #124. Please, continue the conversion there.
