### ISSUE TITLE
Does ijsconsole Support Persistent History?

### ISSUE THREAD

**Issue by dosentmatter** [n-riesco/ijavascript#136]
Does ijsconsole Support Persistent History? I read that ipython stores it in an [sqlite database](https://stackoverflow.com/questions/30629390/where-is-the-history-file-for-ipython). I don't see anything for ijsconsole. An sqlite database isn't necessary. A basic plain text history file is good enough.

**Comment by n-riesco** [comment]
No, it doesn't. I haven't implemented that feature (yet) in the IJavascript
kernel (since execution history is language-independent, I wish frontends
would implement this feature, rather than having every kernel to
reimplement it).

**Comment by dosentmatter** [comment]
Oh okay. Thanks for the quick response. I'm gonna close this issue for now.
