### ISSUE TITLE
Installation of IJavascript using Anaconda installed by root (sudo su) in Ubuntu 16.04

### ISSUE THREAD

**Issue by sigurdurb** [n-riesco/ijavascript#145]
I'm on Ubuntu 16.04 LTS with Jupyterhub 0.8.1, jupyter 4.4.0

A little backstory:
In the instructions it says you can do this when you have everything in conda anyway:
conda install nodejs 
npm install -g ijavascript
This however does not work.

That step resulted in the similar permission error for zmq as some other people have had. Someone said I should install nodejs globally, I'm not sure how to install globally with conda, it does'nt provide flags for installing packages specifically global. It seemed the permission was because it lacked permission to get to /root/.npm but I was running the commands as root.

Here is where npm/node/nodejs was installed in conda and versions:
```
root@jupyter:# which node
/opt/conda/bin/node
root@jupyter:# node --version
v8.9.3
root@jupyter:# which nodejs
/usr/bin/nodejs
root@jupyter:# nodejs --version
v4.2.6
root@jupyter:# which npm
/opt/conda/bin/npm
root@jupyter:# npm --version
5.5.1
```

So I ended up installing nodejs and npm through apt-get
```
sudo su
apt-get install nodejs-legacy npm
/usr/bin/npm install -g ijavascript
ijsinstall
```

Now this is the versions and where they are installed
```
root@jupyter:# which node
/usr/bin/node
v4.2.6
root@jupyter:# node --version
v4.2.6
root@jupyter:# which nodejs
/usr/bin/nodejs
root@jupyter:# nodejs --version
root@jupyter:# which npm
/usr/bin/npm
root@jupyter:# npm --version
3.5.2
```
Running ijsinstall, then the kernel is installed into /root, so I had to cd into /root/.local/share/jupyter/kernels
and then execute
jupyter kernelspec install dir
i.e. `jupyter kernelspec install javascript`

and this install method worked!
But starting a notebook I am getting an error on line 190 in /usr/local/lib/node_modules/ijavascript/lib/kernel.js

This is the debug log from /var/log/jupyterhub/jupyterhub.log:
```
[I 2018-02-12 15:02:28.302 SingleUserNotebookApp restarter:103] KernelRestarter: restarting kernel (2/5)
KERNEL: ARGV: [ '/usr/bin/nodejs',
  '/usr/local/bin/ijskernel',
  '--hide-undefined',
  '-h',
  '/home/sigurdur/.local/share/jupyter/runtime/kernel-9c5bff57-ed88-4b3d-aa3f-ab593feda4a3.json',
  '--protocol=5.0' ]
Usage: node kernel.js [--debug] [--hide-undefined] [--protocol=Major[.minor[.patch]]] [--session-working-dir=path] [--show-undefined] [--startup-script=path] connection_file
/usr/local/lib/node_modules/ijavascript/lib/kernel.js:190

```

Here is that code. The error is always thrown in: `throw new Error("Error: too many arguments");`
```
    try {
        var connectionFile;

	process.argv.slice(2).forEach(function(arg) {
          for(var i = 0; i < FLAGS.length; i++) {
	        var flag = FLAGS[i];
	        var label = flag[0];
	        var action = flag[1];

	        var matchesFlag = (arg.indexOf(label) === 0);
		if (matchesFlag) {
                    var setting = arg.slice(label.length);
                    action(setting);
                    return;
	        }
            }

            if (connectionFile) {
                throw new Error("Error: too many arguments");
	    }

	    connectionFile = arg;
	});

	if (!connectionFile) {
	    throw new Error("Error: missing connection_file");
	}

	config.connection = JSON.parse(fs.readFileSync(connectionFile));

    } catch (e) {
        console.error("KERNEL: ARGV:", process.argv);
        console.error(usage);
	throw e;
    }
```

Commenting out that line and the kernel seems to work fine, I am not sure what this is doing, the "if (connectionFile)" and then outside the loop "if (!connectionFile)" doesn't seem very intuitive.

But I would like to know if this is a real issue with the arguments(see the debug log) or if this should maybe be fixed in the repo.

**Comment by n-riesco** [comment]
1. The first point I want to make is a word of caution about using `sudo su`. When you run:
```
sudo su
npm install -g ijavascript
ijsinstall
```
`sudo su` logs you into the root account (you rarely want to do this; many programs refuse/fail to run/install when run by root).

By default, `ijsinstall` installs IJavascript's kernelspec locally (in this case, the root account and thus only accessible by root).

2. The second point is that, as far as I know, [Anaconda doesn't recommend installations by root](https://docs.anaconda.com/anaconda/install/#general-installation-information).

The instructions to install IJavascript using a local installation of Anaconda in Ubuntu are:
```
conda install nodejs
npm install -g ijavascript
ijsinstall
```

Note that these instructions don't use `sudo` (not even for running `npm install -g ijavascript`).
I've just tested these instructions and they work form me.

3. Let's say, I haven't put you off and you still want to install IJavascript using Anaconda installed by root. Here are the instructions to install IJavascript:

```
mkdir ijavascript
cd ijavascript
npm install ijavascript
$(npm bin ijsinstall)/ijsinstall --spec-path=full
```

**Comment by sigurdurb** [comment]
Thanks for a quick response, 
I tried installing again as root and now the same error does not appear again. I double checked /usr/local/lib/node_modules/ijavascript/lib/kernel.js and it is normal and should throw the error, and it also works for other users I had not tried. Somehow it works now and I have no idea why. So maybe it will change again.

I did try running what you proposed in step 3 as a non root user and it only enabled the javascript kernel for that user but not all users in Jupyterhub.

I guess installing anaconda as non-root would be a good idea, but that would mean every student could just change or install/uninstall packages for everybody, since we are not running jupyterhub in docker because of nbgrader but all users are on the same system I am not sure that is a good idea as we want everyone to have the same versions during assignments for example. Specially during the grading for nbgrader if one student had another version that could end badly. 

Let me know if you have any more questions/suggestions.

**Comment by n-riesco** [comment]
> I tried installing again as root and now the same error does not appear again. I double checked /usr/local/lib/node_modules/ijavascript/lib/kernel.js and it is normal and should throw the error, and it also works for other users I had not tried. Somehow it works now and I have no idea why. So maybe it will change again.

Out of curiosity, does the kernel installed in that way run as root or as the user that launches the kernel? You can check this by running `os.userInfo()` from IJavascript.

> I did try running what you proposed in step 3 as a non root user and it only enabled the javascript kernel for that user but not all users in Jupyterhub.

If you want to install the kernel spec for all the users you need to add the flag `--install=global`, like this:

```
sudo $(npm bin ijsinstall)/ijsinstall --spec-path=full --install=global`
```

Note the use of `sudo` in this case.

You can get a list of all the avaliable flags by running `ijsinstall --help`. In particular, the flag `--startup-script` is very useful if you need to preload any packages at the start of an IJavascript session.

> I guess installing anaconda as non-root would be a good idea, but that would mean every student could just change or install/uninstall packages for everybody, since we are not running jupyterhub in docker because of nbgrader but all users are on the same system I am not sure that is a good idea as we want everyone to have the same versions during assignments for example. Specially during the grading for nbgrader if one student had another version that could end badly.

Since all the students will work on the same machine, I see why [a silent installation](https://docs.anaconda.com/anaconda/install/#silent-mode-install) for each user wouldn't scale well.

This is the first time I've tried to install anaconda as root, so I don't really know what implications this may have. I use Anaconda mostly for Windows. For Linux machines, I often use [pip to install jupyter](http://jupyter.org/install).

**Comment by sigurdurb** [comment]
To answer your question I had to upgrade the nodejs version from 4.2.6 to be able to run the userInfo function. Which was probably a good idea since they stop long term support of 4.x in april. That also required me to remove the node modules dir in /usr/local/lib/node_modules/ijavascript and run sudo npm install again because of errors.

> Out of curiosity, does the kernel installed in that way run as root or as the user that launches the kernel? You can check this by running os.userInfo() from IJavascript.

I hope this is secure enough. I still have yet to try the --install=global thing. 
<img width="397" alt="screen shot 2018-02-13 at 21 15 19" src="https://user-images.githubusercontent.com/10588202/36175266-c132565a-1106-11e8-8eb6-fbe9fe97fd63.png">
