### ISSUE TITLE
support for cyclic require

### ISSUE THREAD

**Issue by lab4quant** [n-riesco/ijavascript#149]
Hello, 
is it possible to add cyclic require for javascript kernel?

e.g.

in `a.js`

```js
const a = require('b')
```
while in `b.js`

```js
const b = require('a')
```

the node.js doesn't support this directly, it would be great if `ijavascript` could

**Comment by n-riesco** [comment]
I'm not sure I understand. What do you mean by supporting cyclic `require`'s?

I've just tested `node@6` and this is what it does:
```
$ node
> fs.readFileSync("./a.js").toString()
'module.exports.test = require("./b.js");\n'
> fs.readFileSync("./b.js").toString()
'module.exports.test = require("./a.js");\n'
> require('./a.js')
{ test: { test: [Circular] } }
```

**Comment by lab4quant** [comment]
@n-riesco,  I'm using node 6.9.4

I tested in both Node console and jupyter notebook using ijavascript kernel

I created a dummy package xx, and put 2 files in it:

a.js

```js
const b = require('b');
module.exports = { name: 'a' }
```

b.js
```js
const a = require('a');
module.exports = { name: 'b' }
```

in Node console or jupyter notebook

```sh
>node
>let a = require('xx/a')
Error: Cannot find module 'b'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\xx\a.
js:1:73)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

My expected behavior is even 2 js files requires each other, system can still resolve it and make it work

**Comment by n-riesco** [comment]
@lab4quant I'm guessing the issue is that you're trying to request a local folder as if it were a module. Local folders require their path to start with `/`, `../`, or `./`. See the documentation [here](https://nodejs.org/api/modules.html#modules_folders_as_modules).

**Comment by lab4quant** [comment]
@n-riesco , I put the folder in `AppData\Roaming\npm\node_modules`, this is the global path for npm

from the error message, it's saying it has found a.js, but can't find module b

**Comment by n-riesco** [comment]
> from the error message, it's saying it has found a.js, but can't find module b

and where do you `node` will find 'b'?

**Comment by n-riesco** [comment]
Again, to understand what the problem is, you need to understand the difference between `require('b.js')` and `require('./b.js')`.
