### ISSUE TITLE
zeromq This version of Node.js requires NODE_MODULE_VERSION 59.

### ISSUE THREAD

**Issue by rddill-IBM** [n-riesco/ijavascript#151]
*Issue: 
After following the OSX installation instructions and starting Jupyter Notebook, attempting to create a javascript notebook consistently generates the following error:
```
Error: The module '/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)

```
*Environment:
 - OSX High Sierra Version: 10.13.4
 - node --version : v8.11.1
 - npm --version : 5.6.0

*(Failed) Attempts to Resolve:
 - Remove and reinstall 
 - npm rebuild zmq --update-binary
 - npm rebuild zeromq --update-binary
 - npm rebuild ijavascript --update-binary
 - brew update followed by brew upgrade

**Comment by n-riesco** [comment]
The error message isn't consistent with `node --version` being `v8.11.1`:
- `NODE_MODULE_VERSION 57` suggests IJavascript was installed using `Node v8`
- `NODE_MODULE_VERSION 59` suggests the IJavascript kernel is invoked using `Node v9`

As a workaround you could reinstall IJavascript's kernelspec using full paths: `ijsinstall --spec-path=full`

**Comment by rddill-IBM** [comment]
Thanks for the quick response. 
 - Running ```which node``` returns ```/usr/local/opt/node@8/bin/node```
 - Running ```node --version``` returns ```8.11.1```

How do I determine what node-js kernel is being invoked from jupyter/ijavascript ? Jupyter was installed using these commands from the install sequence on this site:
```
brew install zeromq
pip3 install --upgrade pyzmq jupyter
npm install -g ijavascript
ijsinstall
```

**Comment by rddill-IBM** [comment]
thanks, the --spec-path=full did the trick.

**Comment by whobutsb** [comment]
Hi @rddill-IBM I'm running in to this same issue trying to install the javascript kernel.  Did only running `ijsinstall --spec-path=full` solve the issue for you?  Did you reinstall any additional software, or take any other steps?  Thank you in advance for the help.

**Comment by megamindbrian** [comment]
Uninstalled ijavascript ```npm -g uninstall ijavascript``` then reinstalled and it recompiled and worked. Reinstalling didn't cause it to recompile. Note, the kernel reference in ipython was still in place but my error changed to "Cannot find module node_modules/ijavascript/... etc"

**Comment by n-riesco** [comment]
@megamindbrian I'm not sure I understand. If the error is still present, could you post the commands you've run and their output?

**Comment by zmays** [comment]
I'm getting the same thing, though I'm starting from this dockerfile: https://github.com/jupyter/docker-stacks/tree/abdb27a6dfbb304caea773c9b81df0330d917627/all-spark-notebook

```
root@67daab547d6d:/usr/local/lib/node_modules/ijavascript/lib# node kernel.js 
internal/modules/cjs/loader.js:857
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
root@67daab547d6d:/usr/local/lib/node_modules/ijavascript/lib# node -v
v11.14.0
root@67daab547d6d:/usr/local/lib/node_modules/ijavascript/lib# npm -v
6.7.0

```

with this docker image:

```
FROM jupyter/all-spark-notebook

USER root

RUN apt-get update && \
    apt-get install -y nodejs \
    npm

RUN sudo npm install -g ijavascript
RUN ijsinstall --spec-path=full

RUN fix-permissions /home/jovyan
```

build the above dockerfile with:
```
docker build -t local-jupyter .
```

Then run: 
```
docker run --rm -p 8888:8888 -p 4040:4040 -e JUPYTER_ENABLE_LAB=yes local-jupyter
```

You can then docker exec in and run:

```
/usr/local/lib/node_modules/ijavascript/lib# node kernel.js 
```
Which is the first command at the beginning of my post.

**Comment by n-riesco** [comment]
@zmays Please, have a look at the Dockerfile [here](https://github.com/n-riesco/ijavascript/blob/master/test/ijavascript-base-notebook-latest/Dockerfile). Would something like that work for you?

**Comment by zmays** [comment]
Yes that one did work for me, thanks!

**Comment by Practcdi** [comment]
**Make sure Python 3 is installed, then install Jupyter Lab:**

$ pip3 install jupyter
$ pip3 install jupyterlab

**Make sure you have installed the older Node.js < v9 (I'm using v8.11.3 with npm v5.6.0), then install IJavaScript:**

$ npm install -g ijavascript
$ ijsinstall

**If you use the latest version of Node.js, you can install the older version too using npm:**

$ npm install -g node@8.11.3
$ npm install -g npm@5.6.0

nvm use 8.11.3

> If you get any error  then :
nvm install 8.11.3

then again ,
nvm use 8.11.3

Done

now open ,

`jupyter lab` or `jupyter notebook`


# Fixes : 

- It fix the continuos crashing of kernel and zeeomq issue

**Comment by n-riesco** [comment]
@briancullinan did you mean to post https://github.com/n-riesco/ijavascript/issues/151#issuecomment-687205967 here?

**Comment by briancullinan** [comment]
Well it would fix the problem of needing to update zeromq.

**Comment by n-riesco** [comment]
> Well it would fix the problem of needing to update zeromq.

oh you mean, because a universal kernel written in python would make the JS biding for zeromq unnecessary?

**Comment by briancullinan** [comment]
Yes, basically babel-php-transpiler https://www.npmjs.com/package/babel-preset-php but for multiple languages (doable) to python and frameworks (harder) in the context of a jupiter kernel.

**Comment by n-riesco** [comment]
I'm sure a JS-to-Python transpiler would have lots of applications, but it wouldn't stop the need for kernels like IJavascript. IJavascript tries hard to ensure it behaves as the Node.js CLI does (e.g. all standard modules are available from `global`; no need for `var path = require(path)`).

---
 
A quick search:
- https://github.com/PiotrDabkowski/Js2Py

---

Thanks for the link to the blog. I'll give it a go and read it.
