### ISSUE TITLE
node v10 appears to be broken.

### ISSUE THREAD

**Issue by Announcement** [n-riesco/ijavascript#152]
# the issue

n-riesco/ijavascript doesn't appear to be working under *windows 10 latest insider preview*[^1] (this is most likely irrelevant as v8.x.x works just fine under the same environment) *node v10* (this is most likely the problem, a lot was changed, I worked alot with nodejs/node-v8 , node version 10; it has proven to be very problematic and changed/broke a lot of various things.)

since the jupyter output is very long it's at the bottom of the post.

# background information

I use usually compile most things from source, but my current pwsh and node are the precompiled binaries at the time of posting this, i also have a custom pwsh profile (also irrelevant, but just incase you were intereted) my name is jake as you can see and I probably won't bother censoring any sensitive information. 

### `$ node -v`
> - ` v10.0.0`
### `$ npm -v`
> - `6.0.0`
### `$ node -pe 'process.versions'`
> ``` { http_parser: '2.8.0',
>  node: '10.0.0',
>  v8: '6.6.346.24-node.5',
>  uv: '1.20.2',
>  zlib: '1.2.11',
>  ares: '1.14.0',
>  modules: '64',
>  nghttp2: '1.29.0',
>  napi: '3',
>  openssl: '1.1.0h',
>  icu: '61.1',
>  unicode: '10.0',
>  cldr: '33.0',
>  tz: '2018c' }
> ```

I uninstalled node v8 LTS to install node v10 because the installer was causing trouble with it preinstalled.
I also reinstalled all of my global modules.

# debugging process

## uninstalled ijavascript

I uninstalled it again to show the build output afterwards.

### `$ npm uninstall --global ijavascript`
> `removed 68 packages in 3.714s`

## nodejs environment

these are what i have installed globally, I try to keep it to a minimum but some things are just so convenient to have I allow it. please let me know if anything is outdated at the time  of reading it because that means I made an oops somewhere, or if you think I have too many.

### `$ npm list --global --depth=0`
> ```C:\Users\Jake\AppData\Roaming\npm
> +-- flow-bin@0.64.0
> +-- gulp-cli@2.0.1
> +-- jsdoc@3.5.5
> +-- node-gyp@3.6.2
> +-- npm@6.0.0
> +-- prettier@1.12.1
> +-- rollup@0.54.1
> +-- typescript@2.8.3
> +-- webpack@4.8.1
> `-- yo@2.0.2
> ```

## installing n-riesco/ijavascript in a normal prompt.
```
C:\Users\Jake\AppData\Roaming\npm\ijsinstall -> C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\bin\ijsinstall.js
C:\Users\Jake\AppData\Roaming\npm\ijs -> C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\bin\ijavascript.js
C:\Users\Jake\AppData\Roaming\npm\ijskernel -> C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\lib\kernel.js
C:\Users\Jake\AppData\Roaming\npm\ijsconsole -> C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\bin\ijsconsole.js
C:\Users\Jake\AppData\Roaming\npm\ijsnotebook -> C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\bin\ijsnotebook.js

> zeromq@4.6.0 install C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\node_modules\zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install No prebuilt binaries found (target=10.0.0 runtime=node arch=x64 platform=win32)

Downloading libzmq for Windows
Download finished

...

+ ijavascript@5.0.20
added 68 packages from 59 contributors in 64.308s
```

I cut out the warnings for conciseness. 

C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\node_modules\zeromq>if not defined npm_config_node_gyp (node "C:\Users\Jake\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Jake\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\node_modules\zeromq\build\zmq.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaratio
n is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Jake\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Windows_NT 10.0.17666
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jake\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\node_modules\zeromq
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jake\AppData\Roaming\npm-cache\_logs\2018-05-12T15_44_54_282Z-debug.log
```
## installing n-riesco/ijavascript with **Compiler 18.0 Update 2 for Intel 64 Visual Studio 2017 environment**
this is just opening the prompt incase you are unfamiliar. it is the visual studio environment with some extra variables for utilizing the intel compiler collection and some special libraries; by the way my `idp3` environment is `intel distribution python 3`; I also have a `intel distribution python 2`
```
Intel(R) MPI Library 2018 Update 2 for Windows* Target Build Environment for Intel(R) 64 applications
Copyright 2007-2018 Intel Corporation.

Copyright (C) 1985-2018 Intel Corporation. All rights reserved.
Intel(R) Compiler 18.0 Update 2 (package 185)

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.6.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
```
### `activate idp2`
### `npm i -g ijavascript`
C:\Users\Jake\AppData\Roaming\npm\ijskernel -> C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\lib\kernel.js
C:\Users\Jake\AppData\Roaming\npm\ijsinstall -> C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\bin\ijsinstall.js
C:\Users\Jake\AppData\Roaming\npm\ijs -> C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\bin\ijavascript.js
C:\Users\Jake\AppData\Roaming\npm\ijsconsole -> C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\bin\ijsconsole.js
C:\Users\Jake\AppData\Roaming\npm\ijsnotebook -> C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\bin\ijsnotebook.js

> zeromq@4.6.0 install C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\node_modules\zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install No prebuilt binaries found (target=10.0.0 runtime=node arch=x64 platform=win32)

Downloading libzmq for Windows
```

btw it appears to work with idp2 but with a few warnings about not finding libzmq.pdb, and the lack of the `/m` flag (for parallel building)

### `jupyter notebook`

```
[I 10:25:38.476 NotebookApp] Loading IPython parallel extension
[I 10:25:39.304 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 10:25:40.147 NotebookApp] Serving notebooks from local directory: C:\Users\Jake
[I 10:25:40.147 NotebookApp] 0 active kernels
[I 10:25:40.147 NotebookApp] The Jupyter Notebook is running at:
[I 10:25:40.147 NotebookApp] http://localhost:8888/?token=1879ff6ea7e8d40ba2cbec9c6a2c477a3fd4e7aff5cce965
[I 10:25:40.147 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:25:40.147 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=1879ff6ea7e8d40ba2cbec9c6a2c477a3fd4e7aff5cce965
```

at this point I copy paste the url into my browser.

``` command
[I 10:25:40.413 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 10:27:21.249 NotebookApp] 302 GET /?token=1879ff6ea7e8d40ba2cbec9c6a2c477a3fd4e7aff5cce965 (::1) 0.00ms
[I 10:27:51.935 NotebookApp] Creating new notebook in
[I 10:27:57.867 NotebookApp] Kernel started: 995552a1-696e-41ca-b13d-4d1c0cf490b8
[W 10:27:58.291 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180512102507 (::1) 114.46ms referer=http://localhost:8888/notebooks/Untitled5.ipynb?kernel_name=javascript
internal/modules/cjs/loader.js:573
    throw err;
    ^
`
Error: Cannot find module '../build/Release/zmq.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\node_modules\zeromq\lib\index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
[I 10:28:00.191 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
internal/modules/cjs/loader.js:573
    throw err;
    ^

...

Error: Cannot find module '../build/Release/zmq.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Jake\AppData\Roaming\npm\node_modules\ijavascript\node_modules\zeromq\lib\index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
[W 10:28:12.245 NotebookApp] KernelRestarter: restart failed
[W 10:28:12.245 NotebookApp] Kernel 995552a1-696e-41ca-b13d-4d1c0cf490b8 died, removing from map.
ERROR:root:kernel 995552a1-696e-41ca-b13d-4d1c0cf490b8 restarted failed!
[W 10:28:12.290 NotebookApp] 410 DELETE /api/sessions/f175fbf3-b7f5-4eee-bd9d-5b8f8154e416 (::1): Kernel deleted before session
[W 10:28:12.290 NotebookApp] Kernel deleted before session
[W 10:28:12.298 NotebookApp] 410 DELETE /api/sessions/f175fbf3-b7f5-4eee-bd9d-5b8f8154e416 (::1) 7.96ms referer=http://localhost:8888/notebooks/Untitled5.ipynb?kernel_name=javascript

```

> Kernel has died! Would you like to restart?
> No.

if more logs are needed i'll gladly provide them. also willing to add debugging messages into v8/node/jp-kernel/ijavascript if need be, I already know my way around v8 and node pretty well but figured I'd post an issue and ask first before I even begin looking into it in case it's a known issue or you already have an idea what's going on.

**Comment by Announcement** [comment]
idp2

**Comment by n-riesco** [comment]
@Announcement One of IJavascript's dependencies is zeromq.  Zeromq is a native module and binaries are provided for most Node versions. When a binary is not provided (e.g. for Node v10), `npm` tries to compile the native module. For that `python2` is needed. See [here](https://github.com/nodejs/node-gyp#on-windows) other requirements to compile `zeromq`.
