### ISSUE TITLE
Executing shell command from within Notebook

### ISSUE THREAD

**Issue by mayankkaizen** [n-riesco/ijavascript#157]
I am sorry if this has been addressed already but a quick search didn't produce any relevant result. 

We can execute shell command in Notebooks with Python kernel like this -  `!conda list` . Is this feature available for Notebooks with IJavaScript kernel?

**Comment by mayankkaizen** [comment]
Per issue#43, it seems running shell command using `!` is not supported. Though it is not a big drawback, it somehow doesn't go well with the concept of `uniform and consistent` experience in Jupyter Notebooks.  It breaks the workflow at times when I forget that this feature isn't supported.

**Comment by SHND** [comment]
I believe this feature should be added and the issue shouldn't get closed.

**Comment by n-riesco** [comment]
[JavaScript's logical NOT operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators)
