### ISSUE TITLE
No JS kernel listed -> IPython 6.2.1, Windows 10

### ISSUE THREAD

**Issue by hcchengithub** [n-riesco/ijavascript#158]
Installed with: `npm install -g ijavascript` 
No problem, things are installed to `c:\Users\hcche\AppData\Roaming\npm`  

Launched with: `ijsinstall`
Fires up Jupyter notebook on Chrome Web Browser. But there is no JavaScript kernel listed in the `[New]` dropdown menu.

Is there anything I can try? I have tried all experiments in #28 as shown below, problem persists:

    c:\Users\hcche>node c:\Users\hcche\AppData\Roaming\npm\node_modules\ijavascript\lib\kernel.js
    KERNEL: ARGV: [ 'C:\\Program Files\\nodejs\\node.exe',
      'c:\\Users\\hcche\\AppData\\Roaming\\npm\\node_modules\\ijavascript\\lib\\kernel.js' ]
    Usage: node kernel.js [--debug] [--hide-undefined] [--protocol=Major[.minor[.patch]]] [--session-working-dir=path] [--show-undefined] [--startup-script=path] connection_file
    c:\Users\hcche\AppData\Roaming\npm\node_modules\ijavascript\lib\kernel.js:190
            throw e;
            ^
    Error: Error: missing connection_file
        at parseCommandArguments (c:\Users\hcche\AppData\Roaming\npm\node_modules\ijavascript\lib\kernel.js:182:19)
        at Object.<anonymous> (c:\Users\hcche\AppData\Roaming\npm\node_modules\ijavascript\lib\kernel.js:46:14)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Function.Module.runMain (module.js:693:10)
        at startup (bootstrap_node.js:191:16)
        at bootstrap_node.js:612:3

    c:\Users\hcche>npm list -g ijavascript
    C:\Users\hcche\AppData\Roaming\npm
    `-- ijavascript@5.0.20

    c:\Users\hcche>ipython locate
    C:\Users\hcche\.ipython

    c:\Users\hcche>ipython --version
    6.2.1

    c:\Users\hcche>ijs --ijs-debug --ijs-install-kernel
    @rem the above command line launched jupyter notebook on my Chrome Browser but the 'new' pull down does not have the anticipated 'javascript (node.js)' item

    c:\Users\hcche>ijsinstall
    @rem the above command line launched jupyter notebook on my Chrome Browser but the 'new' pull down does not have the anticipated 'javascript (node.js)' item

**Comment by n-riesco** [comment]
I won't be able to look at his until next week, but `ijsinstall` shouldn't
launch the notebook.

What do you get when you run `jupyter --version`?

**Comment by hcchengithub** [comment]
1.
c:\Users\hcche>jupyter.exe --version
4.4.0

2. 
_`ijsinstall` shouldn't launch the notebook_ is an useful clue to me, thank you very much!, I can trace into it myself now . . . . . . .

**Comment by hcchengithub** [comment]
Done! 
I have `jupyter.bat` in my path that confused  `ijsinstall` , sorry for the stupid question.
By the way, the installation is very smooth!
