### ISSUE TITLE
Failure to install IJavascript using Node.js v10

### ISSUE THREAD

**Issue by Kashouryo** [n-riesco/ijavascript#165]
When i follow the  instruction to install ijavascipt, npm throw me these errors.
I have a proper python path it even said the correct location. But still can not find python.

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\think\AppData\Local\Programs\Python\Python37\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\think\AppData\Roaming\npm\node_modules\ijavascript\node_modules\zeromq
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\think\AppData\Roaming\npm-cache\_logs\2018-07-16T21_26_55_942Z-debug.log

**Comment by n-riesco** [comment]
`zeromq` doesn't provide prebuilt binaries for Node 10 yet, though it will [soon](https://github.com/zeromq/zeromq.js/pull/262).

In the meantime, see [here](https://github.com/nodejs/node-gyp#on-windows) the requirement to build zeromq in Windows. Note this requires Python 2.

Alternatively, if you don't mind using Node 8, `zeromq` provides prebuilt binaries for Node 8.

**Comment by Kashouryo** [comment]
Thank you. I just tried on Node8, and it installed with no error present.

**Comment by n-riesco** [comment]
Re #181

**Comment by n-riesco** [comment]
Closing in favour of #184
