### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 57.

### ISSUE THREAD

**Issue by jasonxia23** [n-riesco/ijavascript#166]
Running `ijsnotebook` after `ijsinstall`. But got this error:

```
Error: Module version mismatch. Expected 48, got 57.
```
While running `ipython notebook` succeed.

**Comment by jasonxia23** [comment]
Thanks for you answer. But issue still exits.

Here is my local node versions:
```bash
$ nvm ls
         v4.8.4
        v6.10.0
        v7.10.0
         v8.0.0
         v8.5.0
         v8.9.0
->      v8.11.3
         system
```
And run `nvm use system` still throw this error.

**Comment by n-riesco** [comment]
> And run nvm use system still throw this error.

Without seeing the commands you run and their output I can't help much.

Having said that, since your environment uses multiple multiple node versions, I'd suggest you install IJavascript's kernelspec using full paths; like this:

```
ijsinstall --spec-path=full
```

**Comment by shunmian** [comment]
I also encounter this issue even if I tried uninstall and install with `ijsinstall --spec-path=full`

**Comment by n-riesco** [comment]
@shunmian I'll try to help, but please, could you post the commands you're running and their output?

**Comment by shunmian** [comment]
@n-riesco , thanks for your time! The command I run is 
```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install pkg-config node zeromq
sudo easy_install pip
pip install --upgrade pyzmq jupyter
npm install -g ijavascript
ijsinstall
```
, which is exactly the one documented in the `README.MD` for macOS.

**Comment by n-riesco** [comment]
@shunmian Those are the instructions for a fresh install. The error reported in this issue only happens when `node.js` has been updated after running `ijsinstall`; for example, like this:
- install Node v6
- `npm install -g ijavascript`
- `ijsinstall`
- update to Node v8
- error: `Error: Module version mismatch. Expected 48, got 57.`

I'm sorry but I don't have enough information to help you.

**Comment by panpiotrs** [comment]
Hi,

I tried reinstalling and installing zeromq, ijavascript, rebuilding, using `ijsinstall --spec-path=full`, I updated node and tried again - nothing works. I still get:

`Error: The module '/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 47. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:775:18)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)`

`node -v` v11.9.0
`npm -v` 6.5.0

What should I try to do with this, @n-riesco ?

**Comment by n-riesco** [comment]
@panpiotrs, the log message is telling us that you're running `node v11`, but IJavaScript was installed using `node v5`.

Without knowing the details, I'm guessing you've used `sudo npm install -g ijavascript` to install IJavaScript. Do you really need to? If so, what do you get when you run `sudo npm --versions`?

**Comment by panpiotrs** [comment]
I didn't use `sudo`. After `sudo npm --versions` I see the same versions of npm and node → 6.5.0 and 11.9.0, and some other packages, v8, openssl, etc, nothing related to the problem.
I'm upgrading node with current (never lts) package from https://nodejs.org/ . Before today I had v9, I have no idea where this v5 is coming from.

**Comment by n-riesco** [comment]
@panpiotrs The log message shows IJavascript is installed under `/usr/local/lib/node_modules/`. Doesn't that require admin rights in macOS?

I'd try and get rid of `/usr/local/lib/node_modules/ijavascript`:
- either, rename it: `sudo mv /usr/local/lib/node_modules/ijavascript /usr/local/lib/node_modules/ijavascript.old`
- or delete it: `sudo rm -rf /usr/local/lib/node_modules/ijavascript`

And just to be sure, I'd install IJavascript again: `npm install -g ijavascript`

If zeromq is rebuilt, you should see the following lines:
```
> zeromq@4.6.0 install /home/user/lib/node_modules/ijavascript/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
```

**Comment by panpiotrs** [comment]
```
$ sudo rm -rf /usr/local/lib/node_modules/ijavascript
$ npm install -g ijavascript
/usr/local/bin/ijskernel -> /usr/local/lib/node_modules/ijavascript/lib/kernel.js
/usr/local/bin/ijsinstall -> /usr/local/lib/node_modules/ijavascript/bin/ijsinstall.js
/usr/local/bin/ijsnotebook -> /usr/local/lib/node_modules/ijavascript/bin/ijsnotebook.js
/usr/local/bin/ijs -> /usr/local/lib/node_modules/ijavascript/bin/ijavascript.js

> zeromq@4.6.0 install /usr/local/lib/node_modules/ijavascript/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)



+ ijavascript@5.0.20
added 68 packages from 59 contributors in 7.719s
```

what next? `ijsinstall` or `ijsinstall  --spec-path=full`

**Comment by n-riesco** [comment]
If you have only one version of node installed, then `ijsinstall` should work.

**Comment by n-riesco** [comment]
Umm...

What does `which ijsinstall` show?

Could you also run `jupyter kernelspec list --json` and post here the section for javascript?

**Comment by panpiotrs** [comment]
`which ijsinstall`→`/usr/local/bin/ijsinstall`

`jupyter kernelspec list --json`:
```
"javascript": {
      "resource_dir": "/Users/piotr/Library/Jupyter/kernels/javascript",
      "spec": {
        "argv": [
          "ijskernel",
          "--hide-undefined",
          "{connection_file}",
          "--protocol=5.0"
        ],
        "env": {},
        "display_name": "Javascript (Node.js)",
        "language": "javascript",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
```

**Comment by n-riesco** [comment]
Everything looks ok. This is so intriguing!!!

Could you check if the following fails: `cd /usr/local/lib/node_modules/ijavascript/node_modules/ && node -e "require('zeromq')"`?

Please, let me know if it shows the same error message.

If it does fail, could you also run: `cd /usr/local/lib/node_modules/ijavascript/node_modules/ && node -e "console.log(require.resolve('zeromq'))"`?

**Comment by panpiotrs** [comment]
First one shows the same error message.
Second shows `/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/index.js`

**Comment by n-riesco** [comment]
From you first message I understand, you already tried `cd /usr/local/lib/node_modules/ijavascript/ && npm rebuild zeromq`, didn't you?

**Comment by panpiotrs** [comment]
Yes, I did, and right now again to be sure. 
```
> zeromq@4.6.0 install /usr/local/lib/node_modules/ijavascript/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)



zeromq@4.6.0 /usr/local/lib/node_modules/ijavascript/node_modules/zeromq
```
The error is still there 😮

**Comment by n-riesco** [comment]
I need to go away now, but I'll try to reproduce this issue myself on node v11.

The other lead I'd follow is conda. Conda also provides a nodejs package? Have you installed it? Could it be possible that when you work with conda a different version of nodejs is used?

**Comment by panpiotrs** [comment]
No problem, it can wait, thank you for your time. 

I have it from https://www.anaconda.com/distribution/, graphical installer for Python 3.7. And I'm just using it for `jupyter notebook` which works fine for python, but when I create new notebook with JS it can't run the code and there's this error in CLI. I didn't change or install anything more.

**Comment by PabloRN** [comment]
npm rebuild was enough for me
