### ISSUE TITLE
$$.svg in JupyterLab

### ISSUE THREAD

**Issue by Bluejay47** [n-riesco/ijavascript#170]
I am not even sure this is supposed to work so I apologize if this post is off topic.

The following code

```
var fs = require('fs');
var d3 = require('d3');
var jsdom = require('jsdom');
var { JSDOM } = jsdom;

var document = new JSDOM("<html><body></body></html>");
var svg = d3.select(document.window.document.body).append("svg");

svg.append("rect")
    .attr("width", 80)
    .attr("height", 80)
    .style("fill", "orange");

$$.svg("<svg>" + svg.html() + "</svg>");
```
Generates a rectangle as expected in Jupyter Notebooks, but generates a broken image icon in JupyterLab.

Am I doing something incorrectly or is this a compatibility issue with JupterLab?

Thanks,

**Comment by n-riesco** [comment]
This may be an issue recently fixed in JupyterLab (see https://github.com/jupyterlab/jupyterlab/pull/5610).

**Comment by rudifa** [comment]
@n-riesco @Morikko 

Same problem here and now, on a fresh install of `Anaconda3` with `jupyter-lab` and  `ijavascript `(installed per _In macOS, Homebrew and pip can be used to install IJavascript and its prerequisites:_ instructions.

`$$.svg("<svg><rect width=80 height=80 style='fill: orange;'></svg>"); // does not work - broken image icon`

`$$.html("<svg><rect width=250 height=25 style='fill: orange;'></svg>") // workaround - orange square as advertised`

```
macOS 10.15.7 (19H2)
jupyter-lab --version : 2.2.6
ijsinstall --version: 5.2.0
```

<img width="705" alt="Screenshot 2020-10-31 at 23 10 28" src="https://user-images.githubusercontent.com/172404/97791026-63697280-1bce-11eb-9dec-d76d10decca1.png">

**Comment by n-riesco** [comment]
I'm closing, as `$$.html` works around the issue, and https://github.com/jupyterlab/jupyterlab/pull/5610 suggests the decision to skip rendering SVG elements is deliberate.
