### ISSUE TITLE
Tab auto completion

### ISSUE THREAD

**Issue by Masterxilo** [n-riesco/ijavascript#174]
This should work, at least on known objects, like in the node repl or python (ptpython).

**Comment by n-riesco** [comment]
This should be working. See [here](http://n-riesco.github.io/ijavascript/doc/complete.md.html).

**Comment by Masterxilo** [comment]
You're right. Hmm, maybe it's a bit flaky, because I am pretty sure it did not work in another session I was running earlier. Any troubleshooting advice in case it happens? Reload page I guess... Is there some log I can record/provide when I see it happening again?

**Comment by n-riesco** [comment]
The answer depends on the frontend used to launch the kernel. The IJavascript kernel outputs log messages when the environment variable `DEBUG` is set (usually to `*`). For example, in linux, one could open a terminal and run the following command to open the Jupyter notebook:

```
DEBUG=* ijsnotebook
```

**Comment by n-riesco** [comment]
Closing in favour of #82
