### ISSUE TITLE
Plotting no longer working in ijavascript-plotly & plotly-notebook-js.

### ISSUE THREAD

**Issue by thisisloze** [n-riesco/ijavascript#186]
I am trying to learn js and I really like the idea of having jupyter notebooks + ijavascript. I have them working very well together but am having troubles charting anything. Any suggestions?

I have tried both of these examples.

```
const Plotly = require("ijavascript-plotly");

Plotly([{y: [10, 30, 20]}], {title: "Plotly from IJavascript"});

&&

var Plot = require('plotly-notebook-js');
var NotebookPlot = Plot.createPlot().constructor;
NotebookPlot.prototype._toHtml = NotebookPlot.prototype.render;
Plot.createPlot([{ x: [1,2,3], y: [3,4,5] }], { title: 'Plotly in Jupyter!' });

```

**Comment by n-riesco** [comment]
Do you get any any error messages?
If you don't get any: what version of jupyter notebook are you using (`jupyter notebook --version`)?

**Comment by thisisloze** [comment]
There are no error messages in the browser and or google console on chrome. The cell is just blank.
My jupyter notebook version is: 5.74

**Comment by thisisloze** [comment]
Should I be using an older version?

**Comment by MarkDaoust** [comment]
Is this meant to work in a standard jupyter notebook environment?

I'm getting nothing. Using `jupyter --version` `5.7.4`.

@n-riesco, I'd like to use ijavascript for some of my projects.

I see the "application/vnd.plotly.v1+json" in the cell output, but none of the "text/html" outputs that I get using the `python plotly` with `plotly.offline`.

Any suggestions on how to get this to work?

**Comment by n-riesco** [comment]
I, somehow, missed @MarkDaoust 's comment. For anyone, trying the `text/html` approach see http://n-riesco.github.io/ijavascript/doc/custom.ipynb.html#Customising-the-MIME-output-of-a-class .

But, beware that this approach wouldn't work in most frontends due to CSP.

**Comment by n-riesco** [comment]
I've tested `ijavascript-plotly` with the following frontends:
- `hydrogen@2.16.3` works out of the box
- `nteract@0.28.0` works out of the box
- `jupyterLab@3.2.4` requires `pip3 install plotly` to work.
- `notebook@6.4.6` doesn't work
