### ISSUE TITLE
I wish to create YouTube Video

### ISSUE THREAD

**Issue by JupyterJones** [n-riesco/ijavascript#187]
May I use the page https://n-riesco.github.io/ijavascript/doc/custom.ipynb.html in a YouTube Video.
I am starting a Channel JupyterJones and wish to show their ability to run NodeJs and JavaScript.
I will credit the two locations:
https://n-riesco.github.io/ijavascript/doc/custom.ipynb.html
https://github.com/n-riesco/ijavascript
I will notify you when the video is posted
 If you do not like the video when posted I will remove it.

**Comment by n-riesco** [comment]
@JupyterJones Sorry about the late response. 

Very happy to hear about your plans. 

I'm distributing https://n-riesco.github.io/ijavascript/doc/custom.ipynb.html and the documentation under `doc/` under [the same license terms as the code (i.e. BSD-3-clause)](https://github.com/n-riesco/ijavascript/blob/master/LICENSE).

---

I'm looking forward to the video!
