### ISSUE TITLE
a recipe to install on jupyter/base-notebook based on ubuntu-18.04 

### ISSUE THREAD

**Issue by parmentelat** [n-riesco/ijavascript#188]
hey there

in case that's of any interest, I'd like to point at a Dockerfile that successfully installs ijavascript on top of the latest jupyter/base-notebook docker image from docker-stacks

this build sequence is a little tricky because the base image, a ubuntu-18.04, has no python2 installed, but that's a requirement for npm-installing because of an - unbelievable - dependency to python2 in gyp

https://github.com/parmentelat/scratch-js/blob/787d35abf419995952fa2786d7c204998da09cea/nbhosting/Dockerfile

hope this helps

**Comment by parmentelat** [comment]
I should have added that this repo is a temporary thing, and I will probably trash it at some point, so it feels best if I paste it inline


```
# as of today this is python-3.7.1
FROM jupyter/base-notebook:latest

# for nbhosting
USER root
COPY start-in-dir-as-uid.sh /usr/local/bin

# prerequisites with apt-get
# we do install python(2) here because
# some npm build part named gyp still requires it
RUN apt-get update && apt-get install -y gcc g++ make python

# !!! dirty trick!!!
# original PATH is
# /opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# move conda's path **at the end**
# so that python resolves in /usr/bin/python(2)
# but node is still found in conda
ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin"
USER jovyan
RUN npm install -g ijavascript
RUN ijsinstall

# for displaying html fragments
RUN npm install -g jsdom d3

# !!! clean up!!!
USER root
RUN apt-get autoremove -y python
ENV PATH="/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
USER jovyan

```

**Comment by parmentelat** [comment]
final note, it appears that I had to also do this in the Dockerfile

ENV NODE_PATH="/opt/conda/lib/node_modules/"

as by default in this setup, `node` would search in `/opt/conda/lib/node/`

of course this is totally unrelated to the python2 issue that I wanted to describe at first, but well..
and if somebody knows or understands node and npm seem to be out of sync like this, I'd really love to know :)

**Comment by n-riesco** [comment]
@parmentelat Thank you for reporting your findings here.

I'd happily accept a Dockerfile like this as a contribution; for example under `test/ijavascript-base-notebook-latest`.

If you go ahead and decide to contribute, please read [the contribution guidelines](https://github.com/n-riesco/ijavascript/blob/master/CONTRIBUTING.md#code-contributions); especially the bit about the LICENSE and updating AUTHORS.
