### ISSUE TITLE
Include a logo

### ISSUE THREAD

**Issue by rgbkrk** [n-riesco/ijavascript#19]
If you put PNGs named "logo-32x32.png" and "logo-64x64.png" with the kernel spec (kernel.json), the Jupyter Notebook will pick up the logo for you!

Options:

![image](https://cloud.githubusercontent.com/assets/836375/7403807/5bd0083e-ee9f-11e4-9c07-60532f2f0081.png)

![image](https://cloud.githubusercontent.com/assets/836375/7403819/83e0c1a6-ee9f-11e4-82ab-802405b9e0f5.png)

The iojs logo is a decent fit too. :wink:

On a side note, it might be helpful to make the `ijs` script take an option that just installs the kernelspec instead of launching the notebook server + installing the kernel spec. Awesome work, thank you for this.

**Comment by n-riesco** [comment]
Actually, I'm currently working on this. I'll come back to you on this soon.
