### ISSUE TITLE
kernelspec

### ISSUE THREAD

**Issue by seifoorisara** [n-riesco/ijavascript#194]
Hi,
I am using UBUNTU 18.04.
I want to use jupyter for using RapidWright, but I cannot run these instructions?
what should I do?

(base) user@parsapc1000:~$ java com.xilinx.rapidwright.util.RapidWright --create_jupyter_kernel
Wrote Jupyter Notebook Kernel File: '/home/user/jython27/kernel.json'

You can install the RapidWright (Jython 2.7) kernel by running:
    $ jupyter kernelspec install /home/user/jython27
and list currently installed kernels with:
    $ jupyter kernelspec list
(base) user@parsapc1000:~$ sudo jupyter kernelspec install /home/user/jython27
[sudo] password for user: 
Error executing Jupyter command 'kernelspec': [Errno 2] No such file or directory
(base) user@parsapc1000:~$

**Comment by n-riesco** [comment]
@seifoorisara Did you mean to open this issue here?

RapidWright's repository is at https://github.com/Xilinx/RapidWright/issues .
