### ISSUE TITLE
Determine if code running inside IJavascript

### ISSUE THREAD

**Issue by marks6i** [n-riesco/ijavascript#198]
Is it possible to determine in code if the code is running inside IJavascript?  I'd like to develop my code in a Jupyter notebook and then 'Download As...'  into a Node JS script file and have it be executable without further edits.  To do this, I need to be able to run / bypass code with a conditional check if it is running inside IJavascript or not.

I am able to do this with Python notebooks and would like to do this with Node JS notebooks. Perhaps a global variables exists when run from inside IJavascript that I can check?  Thanks in advance.

**Comment by n-riesco** [comment]
Yes, IJavascript defines the global `$$`. See [here](https://github.com/n-riesco/ijavascript/blob/master/doc/async.ipynb) and [here](https://github.com/n-riesco/ijavascript/blob/master/doc/custom.ipynb) for some of the functionality provided through `$$`.
