### ISSUE TITLE
Requiring external packages

### ISSUE THREAD

**Issue by rgbkrk** [n-riesco/ijavascript#20]
Where do packages get pulled from? It's not picking up globally installed packages for me.

**Comment by n-riesco** [comment]
`ijs` should behave like the `node.js` REPL. If it doesn't, I'll consider it a bug.

If you can require the package in the `node.js` REPL:
```
$ node
> require("mypackage")
```
but you can't:
```
$ ijs
In[1]: require("mypackage")
```
please, file a bug including:
* the IJavascript version you're using (`npm list ijavascript`)
* and, if public, the package that `ijs` fails to require.

**Comment by rgbkrk** [comment]
Since I posted this, I'm able to get at the package I want which was `zmq`. ¯\_(ツ)_/¯ Sorry for the noise.
