### ISSUE TITLE
Having Issues with running JavaScript

### ISSUE THREAD

**Issue by KHarrison99** [n-riesco/ijavascript#203]
Hello, I am trying hydrogen and atom for first time.

I have installed iPython and got it working correctly. Very happy with the functionality.

I tried installing iJavascript, managed to get it installed successfully.

I am running latest Linux Mint, latest Atom and latest iJavascript versions.

It discovered the kernel correctly for iJavaScript.

When I try to run basic commands like prompt() or alert() I receive the same error.

Example:
`prompt("test");`

Output:
```

evalmachine.<anonymous>:1
prompt('test');
^

ReferenceError: prompt is not defined
    at evalmachine.<anonymous>:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at run ([eval]:1054:15)
    at onRunRequest ([eval]:888:18)
    at onMessage ([eval]:848:13)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
```

**Comment by n-riesco** [comment]
`prompt` and `alert` are defined when Javascript runs in browser session. IJavascript provides a Node.js session.

See [here](https://nodejs.org/api/index.html) the API provided by Node.js, and [here](http://n-riesco.github.io/ijavascript/doc/async.ipynb.html) and [here](http://n-riesco.github.io/ijavascript/doc/custom.ipynb.html) the API provided by IJavascript.

**Comment by KHarrison99** [comment]
Thanks very much! My mistake, still learning, thought I set it up incorrectly
