### ISSUE TITLE
Error parsing Jupyter version: jupyter core     : 4.6.1

### ISSUE THREAD

**Issue by sildeag** [n-riesco/ijavascript#207]
`sudo ijsinstall --install=global`
results in:
`Error parsing Jupyter version: jupyter core     : 4.6.1` 
`jupyter-notebook : 6.0.2`
`qtconsole        : 4.6.0`
`ipython          : 7.11.1`
`ipykernel        : 5.1.3`
`jupyter client   : 5.3.4`
`jupyter lab      : 1.2.5`
`nbconvert        : 5.4.0`
`ipywidgets       : 7.5.1`
`nbformat         : 4.4.0`
`traitlets        : 4.3.3`
Tried removing and reinstalling but nothing eliminates this issue.   Any ideas?  Operating system `Ubuntu 19.10`  `npm version 6.13.4` `nodejs version 13.6`

**Comment by sildeag** [comment]
Installed `nvm` and changed approach to one not using `sudo`

**Comment by n-riesco** [comment]
I couldn't reproduce the issue against jupyter-core v4.6.1 and IJavascript v5.2.0.

For anyone coming across this issue, please, include the output of running `ijsinstall --versions`.
