### ISSUE TITLE
Error installing ijavascript in Mac OS Mojave

### ISSUE THREAD

**Issue by n-riesco** [n-riesco/ijavascript#211]
I'm having the same problem as reported in this issue, I'm trying to install it on macOS Mojave, that's what I get.
```
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/btm/.npm/_logs/2020-02-29T19_04_21_948Z-debug.log
```
[2020-02-29T19_04_21_948Z-debug.log](https://github.com/n-riesco/ijavascript/files/4270844/2020-02-29T19_04_21_948Z-debug.log)

_Originally posted by @bernardo0marques in https://github.com/n-riesco/ijavascript/issues/193#issuecomment-592984819_

**Comment by n-riesco** [comment]
This seems to be a known [issue](https://ethereum.stackexchange.com/questions/72743/failed-to-install-truffle-on-macos-mojave)/[feature](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) in Mojave.

I'm going to propose three solutions, but as I'm not familiar with Mojave's permissions policy, I can't tell which one I'd recommend:

1. **Reinstall node using a Node version manager**: see a list of managers [here](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm#osx-or-linux-node-version-managers)

2. **Set a local install folder**: `npm config set prefix $HOME`

3. **Install using admin permissions**: `sudo npm install -g --unsafe-perm ijavascript`

**Comment by pritesh-shrivastava** [comment]
I faced a similar issue in MacOS Mojave. For me, adding the `conda install nodejs` command worked.
