### ISSUE TITLE
Syntax highlighting in Jupyter notebook/lab

### ISSUE THREAD

**Issue by nathancarter** [n-riesco/ijavascript#212]
I notice that several places where IJavascript is used (for example, the [Hello World!](http://n-riesco.github.io/ijavascript/doc/hello.ipynb.html) notebook) show syntax highlighting in the Jupyter notebook.  I couldn't find anything that told me how to ensure that, though.  I'm using ijs version 5.2.0 and Jupyter Lab version 1.0.2.

**Comment by nathancarter** [comment]
Hmm.  If I run `jupyter notebook` instead of `jupyter lab`, this works fine.  So this must be an nbextension that doesn't work in lab, I guess?  Maybe this isn't an issue then...?

**Comment by n-riesco** [comment]
This issue is fixed in Jupyter Lab 1.0.3 (see https://github.com/jupyterlab/jupyterlab/pull/6860 ).

Anyway, I'll mark this issue as a bug in IJavascript, so that I don't forget to fix the `kernel_info_reply` message that triggers this issue in JupyterLab.

**Comment by n-riesco** [comment]
Closed in favour of #258
