### ISSUE TITLE
Cannot Run ijsinstall in ubuntu 18.04 or 18.04.4 (command not found)

### ISSUE THREAD

**Issue by NathanK20** [n-riesco/ijavascript#217]
I have installed Jupyter Notebook, alone, not through conda, and I am trying to enable a javascript kernel, but it seems like it only has support for 16.04 or 19.04 and I really don't want to update or rollback my OS. I have resolved a majority of the issues, but they all come back to the fact that I cant run ijsinstall, it just gives me a "command not found" error. I have tried manually running the javsacript files for ijsinstall, ijskerenel, ijsconsole, ijsnotebook, ect. and that got the notebook working, but it just gives me a kernel error with web.py and other files. I would really appreciate some help

**Comment by n-riesco** [comment]
Last time I checked Ubuntu 18.04, I used 18.04.3 and it was working. Please, could you post what steps you've followed to install Node.js and IJavascript?

This should help us find out why the IJavascript executables aren't accessible from your PATH.

The error the Jupyter Notebook may also give a clue.

**Comment by saber-project** [comment]
i,am beginners, please help...
this is my error!
ubuntu 18.04.3
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
sudo apt-get install nodejs-legacy npm ipython ipython-notebook
[sudo] password for sns: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'nodejs' instead of 'nodejs-legacy'
Package ipython-notebook is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ipython-notebook' has no installation candidate
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by n-riesco** [comment]
@saber-project My bad. I've just fixed the instructions in [README.md](https://github.com/n-riesco/ijavascript#ubuntu) (wrong version number).

Please, try again with the instructions [there](https://github.com/n-riesco/ijavascript#ubuntu) for Ubuntu 18.04.

**Comment by saber-project** [comment]
first，thanks for your response！
but have other problem.
My system has installed node.js (v12.16.2 LTS) and Annaconda 3 (Anaconda3-2020.02-Linux-x86_64.sh)

>>>>problem 1>>>>
(base)XXX@ubuntu:~/project$ sudo apt-get install nodejs npm jupyter-notebook
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (12.16.2-1nodesource1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs : Conflicts: npm
E: Unable to correct problems, you have held broken packages.

********************************************************
so, I tried another command, process as follows:
********************************************************

(base) XXX@ubuntu:~/project$ npm install jupyter-notebook
npm WARN saveError ENOENT: no such file or directory, open '/home/sns/project/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/sns/project/package.json'
npm WARN project No description
npm WARN project No repository field.
npm WARN project No README data
npm WARN project No license field.
+ jupyter-notebook@0.0.0
added 1 package from 1 contributor and audited 1 package in 2.57s
found 0 vulnerabilities

(base) XXX@ubuntu:~/project$ sudo npm install -g --unsafe-perm ijavascript
/usr/bin/ijs -> /usr/lib/node_modules/ijavascript/bin/ijavascript.js
/usr/bin/ijsconsole -> /usr/lib/node_modules/ijavascript/bin/ijsconsole.js
/usr/bin/ijsinstall -> /usr/lib/node_modules/ijavascript/bin/ijsinstall.js
/usr/bin/ijskernel -> /usr/lib/node_modules/ijavascript/lib/kernel.js
/usr/bin/ijsnotebook -> /usr/lib/node_modules/ijavascript/bin/ijsnotebook.js

> zeromq@5.2.0 install /usr/lib/node_modules/ijavascript/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
+ ijavascript@5.2.0
added 67 packages from 65 contributors in 58.043s

(base) XXX@ubuntu:~/project$ sudo ijsinstall --install=global
Error running `jupyter --version`
Error: Command failed: jupyter --version
/bin/sh: 1: jupyter: not found

Error running `ipython --version`
Error: Command failed: ipython --version
/bin/sh: 1: ipython: not found
<<<<problem 1<<<<

***********************************************************************************
but i tried command alone.   'jupyter --version' and 'ipython --version' existed
***********************************************************************************

(base) XXX@ubuntu:~/project$ jupyter --version
jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : 4.6.0
ipython          : 7.12.0
ipykernel        : 5.1.4
jupyter client   : 5.3.4
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
(base) sns@ubuntu:~/project$ ipython --version
7.12.0

i do not know how to solve....

**Comment by n-riesco** [comment]
First of all , you need to decide whether you want to install node.js from ubuntu's repositories or from conda's.

The instructions reported by other users of conda can be found [here](http://n-riesco.github.io/ijavascript/doc/install.md.html#conda).

The error you get when installing from ubuntu's repositories:
```
$ sudo apt-get install nodejs npm jupyter-notebook

[...]

The following packages have unmet dependencies:
nodejs : Conflicts: npm
```

suggests you need to update the package information, like this:

```
$ sudo apt update
```

and then try again

```
$ sudo apt-get install nodejs npm jupyter-notebook
```

**Comment by saber-project** [comment]
![Capture](https://user-images.githubusercontent.com/36060944/79705238-d7af7a80-8269-11ea-9b15-27a84d46dff1.PNG

**Comment by saber-project** [comment]
[https://www.npmjs.com/search?q=jupyter-notebook](url)
in npm, 'jupyter-notebook' is No longer updated and supported ?

**Comment by saber-project** [comment]
Finally succeeded！！
My system has installed node.js (node-v12.16.2-linux-x64.tar.gz) and Annaconda 3 (Anaconda3-2020.02-Linux-x86_64.sh), So perform the following steps in the conda environment (my conda environment name is base)

To install IJavascript in Ubuntu 18.04 for all users as follows:

First Step: install node.js (npm will automatically install), there are two methods (Choose only one of the two methods):
* first method-->download 'node-v12.16.2-linux-x64.tar.gz' and install
* second method-->excute command: 'sudo apt-get install nodejs npm jupyter-notebook'

Second Step: excute command
* sudo npm install -g --unsafe-perm ijavascript

Third Step: not excute 'sudo ijsinstall --install=global',   please excute this command
* ijsinstall

**Comment by n-riesco** [comment]
Note that the instructions you've posted install node.js and ijavascript globally (i.e. not in conda's environment). Thus, the need for `sudo npm install -g --unsafe-perm ijavascript` and `sudo ijsinstall --install=global`.

**Comment by saber-project** [comment]
You are right, this is the step of global installation.

But I mean, I switched to the above operations in the command line environment of conda.
`xxx@ubuntu:~$ conda env list
  
#conda environments:  
  #base    /home/xxx/anaconda3

xxx@ubuntu:~$ conda activate

(base) xxx@ubuntu:~$  
`
For me, after executing ‘sudo ...’ in the first two steps,  the third step cannot be executed succeed  ‘sudo ijsinstall --install=global’，i do not known why. 
Thus, I try to execute 'ijsinstall', after execution, it is all success.

so be it,  Thanks a lot.

**Comment by n-riesco** [comment]
what do you get when you run `which jupyter` before and after activating the conda env?

**Comment by saber-project** [comment]
When conda env is not activated, my jupyter notebook cannot be started. 
`
(base) xxx@ubuntu:~$ conda deactivate

xxx@ubuntu:~$ jupyter notebook

Command 'jupyter' not found, but can be installed with:
sudo snap install jupyter       # version 1.0.0, or
sudo apt  install jupyter-core
See 'snap info jupyter' for additional versions.
`
When conda env is activated, jupyter notebook can be started normally. 

So I chose to install the 'ijsinstall' after activating conda env.

**Comment by n-riesco** [comment]
OK, that error indicates jupyter has been installed using conda only.

In that case, [here are some installation notes](http://n-riesco.github.io/ijavascript/doc/install.md.html#conda) contributed by other conda users that may be useful to you.

**Comment by n-riesco** [comment]
@saber-project I'm closing this issue. Feel free to reopen.
