### ISSUE TITLE
Can't Install In Dockerized Conda Environment

### ISSUE THREAD

**Issue by tarfeef101** [n-riesco/ijavascript#227]
I'm trying to install this inside of a dockerized environment with multiple conda environments within it. However, there really doesn't seem to be any consideration, documentation, or support for such a use case. What I'm trying to do is essentially (within the context of a Dockerfile):

```
COPY node10.yaml node12.yaml /opt/conf_files/
RUN /opt/conda/bin/conda env create -f /opt/conf_files/node10.yaml
RUN /opt/conda/bin/conda env create -f /opt/conf_files/node12.yaml
WORKDIR /opt/conda/envs/node10/
RUN ./bin/npm install -g ijavascript && ./bin/ijsinstall --install=global
WORKDIR /opt/conda/envs/node12/
RUN ./bin/npm install -g ijavascript && ./bin/ijsinstall  --install=global
```

Those `.env` files just specify a node version and the `jupyter` package (though I've also tried without the latter, however this doesn't really matter because I can't get to the point where that would be needed).

I've played around with various flags but nothing really seems to address the main issue of: "how do I install within a conda environment from inside a dockerfile, where running `conda activate` or `source activate` aren't possible, and keep the installation local to that environment"?

I've run into a couple errors, including:
```
Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ijavascript/node_modules/zeromq/zmq'
```
during the `npm install`, or
```
prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
```
just before that error (only a warning, but things going into a user directory sounds unhelpful given the context of trying to install this into an environment, not a user's homedir).

When I changed my command to: `RUN /opt/conda/envs/node10/bin/npm install ijavascript && /opt/conda/envs/node10/bin/ijsinstall`, I got `npm install` to pass, but then got this error:
```
/bin/bash: /opt/conda/envs/node10/bin/ijsinstall: No such file or directory
```
This seemed to be because the npm install process dropped stuff into the working directory, which was equally unhelpful. 

Any help with getting this configuration working would be greatly appreciated. Sadly the conda package is outdated, and the install process recommended in its stead isn't possible in a Dockerfile

**Comment by n-riesco** [comment]
I'm unable to test this right now, but here are a few pointers:
- don't you need to activate the env? (i.e. `conda activate <env-name>`)
- running `npm` under the root account to build binary packages requires `--unsafe-perm` (see #146)
- if you're planning to run the IJavascript kernel without activating the env, you may need to install the kernelspec using `ijsinstall --spec-path=full` (see https://github.com/n-riesco/ijavascript/issues/145#issuecomment-365035047)

**Comment by tarfeef102** [comment]
1. No, I have multiple conda environments that were installed without needing to be activated, and by using the binaries located in `/opt/conda/envs/env_name/bin`, you can even use the binaries for that environment, at least to some degree. Regardless, activation of an environment inside a Dockerfile isn't possible, so that's not something I can do.
2. That doesn't really solve the problem, though. The directories that permission is being denied for aren't just access restricted, but rather, they're wrong. They should be installing inside the conda environment, but `/usr/lib` and `/root/` are not part of the conda environment.
3. I can try that (but will also need `--install=global` it seems, since like that issue creator I'm also running a multi-user jupyterhub, with the difference that I'm doing so inside of a container). But I need to get past `npm install` first before I get to that point.

**Comment by n-riesco** [comment]
>     1. No, I have multiple conda environments that were installed without needing to be activated, and by using the binaries located in `/opt/conda/envs/env_name/bin`, you can even use the binaries for that environment, at least to some degree. Regardless, activation of an environment inside a Dockerfile isn't possible, so that's not something I can do.

Usually, one would activate the env where IJavascript will be installed before running `npm` and `ijsinstall`.

>     2. That doesn't really solve the problem, though. The directories that permission is being denied for aren't just access restricted, but rather, they're wrong. They should be installing inside the conda environment, but `/usr/lib` and `/root/` are not part of the conda environment.

Where do you need the binaries for each env to be installed?

>     3. I can try that (but will also need `--install=global` it seems, since like that issue creator I'm also running a multi-user jupyterhub, with the difference that I'm doing so inside of a container). But I need to get past `npm install` first before I get to that point.

`--install=global` only determines the location of the kernelspec. The location where IJavascript is installed is determined by `npm` (e.g. `-g`, `--prefix`). If `npm` was installed using conda, I'd expect the active env to determine the location where `npm` installs the binaries. I'd also expect conda to set `PATH` accordingly.

**Comment by tarfeef101** [comment]
1. Usually, yes. But since I'm inside of a Dockerfile, I can't do that. 
2. That is a question I'm not entirely equipped to answer. I can say my desired state is: when a user logs in to jupyter hub/lab, they can select from a variety of kernels created by conda. currently, these are a few different python kernels. I'd like the ability to have some javascript ones be present. Wherever would enable this to be the case, is the answer. I SUSPECT that is somewhere within `/opt/conda/envs/env_name/*`, but I am not positive as to where specifically. 
3. I specifically do NOT want to be modifying the path during installation. Since this is a Dockerfile specifying the runtime environment for jupyterhub itself, the PATH should remain that of the "root" container environment, not for one of the conda environments which only exist to be available within jupyter. Npm is implicitly installed by conda since it is packed with node (I am planning a node 10 and node 12 kernel), and is located in `/opt/conda/envs/env_name/bin/npm`.

**Comment by tarfeef101** [comment]
I split my install command into 2 parts so I could run the image and inspect the fs, and this is what I found. First, this is what I ran:
```
Step 45/54 : RUN ./bin/npm install --prefix . ijavascript
Step 46/54 : RUN ./bin/node node_modules/ijavascript/bin/ijsinstall.js --install=global --spec-path=full
```
After the first `npm install`, I did not find a single file in the filesystem called `ijsinstall`. None existed. However, `ijsinstall.js` existed in the directory I specified in the 2nd command. So, I tried running the above. 

However, in my jupyterlab instance once everything was finished, I ended up with 2 python kernels representing the conda environments rather than javascript ones, which is obviously not ideal. Then, I also had 1 javascript environment that threw this error in the jupyter logs when I tried to use it:
```
jupyter_temp    | internal/modules/cjs/loader.js:1065
jupyter_temp    |   return process.dlopen(module, path.toNamespacedPath(filename));
jupyter_temp    |                  ^
jupyter_temp    | 
jupyter_temp    | Error: The module '/opt/conda/envs/node12/node_modules/zeromq/build/Release/zmq.node'
jupyter_temp    | was compiled against a different Node.js version using
jupyter_temp    | NODE_MODULE_VERSION 83. This version of Node.js requires
jupyter_temp    | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
jupyter_temp    | the module (for instance, using `npm rebuild` or `npm install`).
jupyter_temp    |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1065:18)
jupyter_temp    |     at Module.load (internal/modules/cjs/loader.js:879:32)
jupyter_temp    |     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
jupyter_temp    |     at Module.require (internal/modules/cjs/loader.js:903:19)
jupyter_temp    |     at require (internal/modules/cjs/helpers.js:74:18)
jupyter_temp    |     at Object.<anonymous> (/opt/conda/envs/node12/node_modules/zeromq/lib/index.js:6:11)
jupyter_temp    |     at Module._compile (internal/modules/cjs/loader.js:1015:30)
jupyter_temp    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
jupyter_temp    |     at Module.load (internal/modules/cjs/loader.js:879:32)
jupyter_temp    |     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

**Comment by n-riesco** [comment]
This error message:
```
jupyter_temp    | NODE_MODULE_VERSION 83. This version of Node.js requires
jupyter_temp    | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
```
means that IJavascript was installed using Node v14, but Jupyter is launching IJavascript using Node v12.

This gives a pointer where one of the issues is.

**Comment by n-riesco** [comment]
>     1. Usually, yes. But since I'm inside of a Dockerfile, I can't do that.

I don't know why it wouldn't be possible. You seem to be able to create the conda env, why wouldn't it be possible to activate it?

>     2. That is a question I'm not entirely equipped to answer. I can say my desired state is: when a user logs in to jupyter hub/lab, they can select from a variety of kernels created by conda. currently, these are a few different python kernels. I'd like the ability to have some javascript ones be present. Wherever would enable this to be the case, is the answer. I SUSPECT that is somewhere within `/opt/conda/envs/env_name/*`, but I am not positive as to where specifically.

Probably, I haven't understood your setup yet. Please, correct me if anything below is incorrect:

- jupyterhub and conda have been installed in the same docker image
- jupyterhub and conda have been installed by the root in the docker image
- the conda envs have been installed by the root
- you are able to setup multiple envs for python

Have you checked whether the python envs are working as expected? (i.e. you can install packages and import them within the env).

I'm not familiar with how jupyter hub and conda envs work together. How does jupyter hub activate the right env? Does it do it out of the box? Or you need to set it up yourself?

>     3. I specifically do NOT want to be modifying the path during installation. Since this is a Dockerfile specifying the runtime environment for jupyterhub itself, the PATH should remain that of the "root" container environment, not for one of the conda environments which only exist to be available within jupyter. Npm is implicitly installed by conda since it is packed with node (I am planning a node 10 and node 12 kernel), and is located in `/opt/conda/envs/env_name/bin/npm`.

My understanding is that conda updates `PATH` when an env is activated.

**Comment by tarfeef101** [comment]
> I don't know why it wouldn't be possible. You seem to be able to create the conda env, why wouldn't it be possible to activate it?
> 
> >

I really don't want to go into the details of why, but essentially it is an interactive shell command, which Dockerfiles are not.



> Probably, I haven't understood your setup yet. Please, correct me if anything below is incorrect:
> 
> * jupyterhub and conda have been installed in the same docker image
> * jupyterhub and conda have been installed by the root in the docker image
> * the conda envs have been installed by the root
> * you are able to setup multiple envs for python
> 
> Have you checked whether the python envs are working as expected? (i.e. you can install packages and import them within the env).
> 
> I'm not familiar with how jupyter hub and conda envs work together. How does jupyter hub activate the right env? Does it do it out of the box? Or you need to set it up yourself?

1. Yes
2. Yes
3. Yes
4. Yes
5. Yes
6. Yes

When you enter jupyterhub, you can select a kernel for your notebook, and it'll use that to execute your code. That's pretty much it. If the kernel exists and has the necessary packages to present itself as jupyter-ready, it'll be there.



> > ```
> > 1. Usually, yes. But since I'm inside of a Dockerfile, I can't do that.
> > ```
> 
> I don't know why it wouldn't be possible. You seem to be able to create the conda env, why wouldn't it be possible to activate it?
> 
> > ```
> > 2. That is a question I'm not entirely equipped to answer. I can say my desired state is: when a user logs in to jupyter hub/lab, they can select from a variety of kernels created by conda. currently, these are a few different python kernels. I'd like the ability to have some javascript ones be present. Wherever would enable this to be the case, is the answer. I SUSPECT that is somewhere within `/opt/conda/envs/env_name/*`, but I am not positive as to where specifically.
> > ```
> 
> Probably, I haven't understood your setup yet. Please, correct me if anything below is incorrect:
> 
> * jupyterhub and conda have been installed in the same docker image
> * jupyterhub and conda have been installed by the root in the docker image
> * the conda envs have been installed by the root
> * you are able to setup multiple envs for python
> 
> Have you checked whether the python envs are working as expected? (i.e. you can install packages and import them within the env).
> 
> I'm not familiar with how jupyter hub and conda envs work together. How does jupyter hub activate the right env? Does it do it out of the box? Or you need to set it up yourself?
> 
> > ```
> > 3. I specifically do NOT want to be modifying the path during installation. Since this is a Dockerfile specifying the runtime environment for jupyterhub itself, the PATH should remain that of the "root" container environment, not for one of the conda environments which only exist to be available within jupyter. Npm is implicitly installed by conda since it is packed with node (I am planning a node 10 and node 12 kernel), and is located in `/opt/conda/envs/env_name/bin/npm`.
> > ```
> 
> My understanding is that conda updates `PATH` when an env is activated.

A great reason NOT to activate (aside from the fact that I can't anyways). Hence why I've been using `/opt/conda/envs/env_name/bin` for this so far.

**Comment by n-riesco** [comment]
>     1. Yes
> 
>     2. Yes
> 
>     3. Yes
> 
>     4. Yes
> 
>     5. Yes
> 
>     6. Yes

Then, I see no reason why it wouldn't be possible to setup the IJavascript kernel similarly.

At this point, your best shot is to figure out why your Dockerfile uses node v14 to install IJavscript. For your setup to work, you need two installations of IJavascript one for node v10 and another for v12.

**Comment by tarfeef101** [comment]
[](url)

> > ```
> > 1. Yes
> > 
> > 2. Yes
> > 
> > 3. Yes
> > 
> > 4. Yes
> > 
> > 5. Yes
> > 
> > 6. Yes
> > ```
> 
> Then, I see no reason why it wouldn't be possible to setup the IJavascript kernel similarly.
> 
> At this point, your best shot is to figure out why your Dockerfile uses node v14 to install IJavscript. For your setup to work, you need two installations of IJavascript one for node v10 and another for v12.

Why? Because conda allows you to install pip packages inside of the environment definition (e.g. an `environment.yml` file, like [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file). Conda, unsurprisingly, will install things properly inside of conda environments.

However, since this is a javascript package, this cannot be done. That's why it cannot be done the same way.

I already know how to install 2 installations of Javascript. That is done. Those conda environments exist. The issue is the installation of this package. This is what I'm doing right now. As you can see, I'm using the correct versions of the `node` executable when I'm calling your installers. Something internal to the code of `ijavasacript` is probably reading the PATH or something and trying to interact with the version of node on the PATH (which will be 14, which is outside of the conda env but is installed for the sake of running the hub itself).
```
RUN /opt/conda/bin/conda env create -f /opt/conf_files/node10.yaml
RUN /opt/conda/bin/conda env create -f /opt/conf_files/node12.yaml
WORKDIR /opt/conda/envs/node10/
RUN ./bin/npm install --prefix . ijavascript
RUN ./bin/node node_modules/ijavascript/bin/ijsinstall.js
WORKDIR /opt/conda/envs/node12/
RUN ./bin/npm install --prefix . ijavascript && ./bin/node node_modules/ijavascript/bin/ijsinstall.js
```

**Comment by n-riesco** [comment]
Please, add `RUN ./bin/npm --versions` after `WORKDIR /opt/conda/envs/node10/` and `WORKDIR /opt/conda/envs/node12/`.

If my understanding is correct, you will discover `npm` is using node.js v14 in both cases.

**Comment by n-riesco** [comment]
Closing as there hasn't been any activity. Please, feel free to reopen.
