### ISSUE TITLE
Cannot find module '../build/Release/zmq.node' Require stack:

### ISSUE THREAD

**Issue by JustGenius-s** [n-riesco/ijavascript#232]
Hi,everyone!
I'm using fedora33, and when i install **ijavascript** for Atom **Hydrogen**, finally i got a problem.

- I'v run `npm install -g ijavascript` to install  **ijavascript**,.

- And run `ijsintall` to install it 
 
But when i run **Hydrogen**, **it reported:**

internal/modules/cjs/loader.js:883 throw err; ^

Error: Cannot find module '../build/Release/zmq.node' Require stack:

/home/Buele/lib/node_modules/ijavascript/node_modules/zeromq/lib/index.js
/home/Buele/lib/node_modules/ijavascript/node_modules/zeromq/index.js
/home/Buele/lib/node_modules/ijavascript/node_modules/jmp/index.js
/home/Buele/lib/node_modules/ijavascript/node_modules/jp-kernel/lib/jp-kernel.js
/home/Buele/lib/node_modules/ijavascript/node_modules/jp-kernel/index.js
/home/Buele/lib/node_modules/ijavascript/lib/kernel.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15) at Function.Module._load (internal/modules/cjs/loader.js:725:27) at Module.require (internal/modules/cjs/loader.js:952:19) at require (internal/modules/cjs/helpers.js:88:18) at Object. (/home/Buele/lib/node_modules/ijavascript/node_modules/zeromq/lib/index.js:6:11) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Module.require (internal/modules/cjs/loader.js:952:19) { code: 'MODULE_NOT_FOUND', requireStack: [ '/home/Buele/lib/node_modules/ijavascript/node_modules/zeromq/lib/index.js', '/home/Buele/lib/node_modules/ijavascript/node_modules/zeromq/index.js', '/home/Buele/lib/node_modules/ijavascript/node_modules/jmp/index.js', '/home/Buele/lib/node_modules/ijavascript/node_modules/jp-kernel/lib/jp-kernel.js', '/home/Buele/lib/node_modules/ijavascript/node_modules/jp-kernel/index.js', '/home/Buele/lib/node_modules/ijavascript/lib/kernel.js' ] }

I have checked file **../build/Release/zmq.node**, and it does't exist.
What should i do to build this file?

**Comment by n-riesco** [comment]
`zeromq@5` doesn't provide pre-built binaries for recent versions of node.js. Without knowing the node.js version in your computer, I'm guessing this is your case.

The dependencies for IJavascript to be able to build `zmq.node` are listed in [doc/install.md.html](http://n-riesco.github.io/ijavascript/doc/install.md.html). Unfortunately, I don't have a section for Fedora. Assuming you already have the necessary Jupyter tools and build tools, you need to install the `zeromq` library. The instructions for Fedora can be found [here](https://zeromq.org/download/):

````
dnf install zeromq-devel
````

Once you've got all the requirements, I'd uninstall IJavascript, to make sure the partially installed `zeromq` is removed, and install IJavascript again.

**Comment by JustGenius-s** [comment]
> `zeromq@5` doesn't provide pre-built binaries for recent versions of node.js. Without knowing the node.js version in your computer, I'm guessing this is your case.
> 
> The dependencies for IJavascript to be able to build `zmq.node` are listed in [doc/install.md.html](http://n-riesco.github.io/ijavascript/doc/install.md.html). Unfortunately, I don't have a section for Fedora. Assuming you already have the necessary Jupyter tools and build tools, you need to install the `zeromq` library. The instructions for Fedora can be found [here](https://zeromq.org/download/):
> 
> ```
> dnf install zeromq-devel
> ```
> 
> Once you've got all the requirements, I'd uninstall IJavascript, to make sure the partially installed `zeromq` is removed, and install IJavascript again.

Thanks for your replay!

Actually my **node version is v14,**  and i've tried to install **zeromq** by `npm install zeromp`.Sounds dumb.

After i tried:
> ```
> dnf install zeromq-devel
> ```
And  i reinstall **ijavascript** , it works.
Really thanks!
