### ISSUE TITLE
Unhandled Error 

### ISSUE THREAD

**Issue by fullstackdetective** [n-riesco/ijavascript#233]
I am unable to start the kernel in jupyter lab. This is what I see...

![Screenshot 2020-12-28 at 9 52 29 AM](https://user-images.githubusercontent.com/72066862/103189423-8a080900-48f2-11eb-9bf0-74090a3e5666.png)

**Comment by fullstackdetective** [comment]
I ran `ijsinstall --spec-path=full` and after which the kernel restarted and I no longer get this error. 

I also update packages in conda.

Hope this helps someone.

**Comment by n-riesco** [comment]
thanks for reporting the issue and the solution,
