### ISSUE TITLE
is there a way to produce HTML content ?

### ISSUE THREAD

**Issue by parmentelat** [n-riesco/ijavascript#234]
Hi

I'm trying to have my ijavascript kernel produce html

the IPython kernel comes with tools like the following, so one can programmatically create html contents

```
from IPython.core.display import display, HTML
display(HTML('<h1>Hello, world!</h1>'))
```

is there something similar within ijavascript, or how could I go about achieving the same kind of result ?

thanks !

**Comment by n-riesco** [comment]
Yes, `$$.html` can do that. [Here's](http://n-riesco.github.io/ijavascript/doc/custom.ipynb.html#$$.html(htmlString)) an example.

**Comment by parmentelat** [comment]
all righty, cool, that's exactly what I was after, thanks !
