### ISSUE TITLE
npm install -g ijavascript doesn´t work here

### ISSUE THREAD

**Issue by nilsinhojrx** [n-riesco/ijavascript#237]
Hello, guys. My name is Nilson and I got a bad error when I was trying to install ijavascript in windows. Please, help me. 

![error ijavascript](https://user-images.githubusercontent.com/72417934/113395034-a2634600-936f-11eb-97d4-3767e6c5b8bc.png)

**Comment by n-riesco** [comment]
`zeromq@5.2.0` doesn't provide pre-built binaries for recent versions of node.js.

See https://github.com/n-riesco/ijavascript/issues/221#issuecomment-784648092 for instructions to build `zeromq`. Let's continue the discussion there, if it doesn't work for you.
