### ISSUE TITLE
Installation error: `ijsinstall: command not found`

### ISSUE THREAD

**Issue by secondl1ght** [n-riesco/ijavascript#241]
I followed the installation commands for Ubuntu but once I got to the 'ijsinstall' command I get the message 'ijsinstall: command not found'. Sorry if this is a simple question but I am trying to get Hydrogen for Atom working with JavaScript and I am trying to install the kernel as instructed so I am able to use this extension. Thanks

**Comment by n-riesco** [comment]
What command did you run to install `ijavascript`? `npm install -g ijavascript`? if so, have you set up the npm prefix?
If you had, but the `~/bin` folder didn't exist before installing `ijavascript`, you may need to log out and back in, for `~/bin` to be added to your `PATH`.

**Comment by secondl1ght** [comment]
Ok I rebooted my laptop and now the command works but I am getting the following output when it runs:

```
Error running `jupyter kernelspec install --replace /tmp/7b2f8a76baa7ae55a19bd075bb022026/javascript --user`
Error: Command failed: jupyter kernelspec install --replace /tmp/7b2f8a76baa7ae55a19bd075bb022026/javascript --user
Traceback (most recent call last):
  File "/usr/bin/jupyter", line 11, in <module>
    load_entry_point('jupyter-core==4.6.3', 'console_scripts', 'jupyter')()
  File "/usr/lib/python3/dist-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/lib/python3/dist-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-kernelspec` not found.

Traceback (most recent call last):
  File "/usr/bin/jupyter", line 11, in <module>
    load_entry_point('jupyter-core==4.6.3', 'console_scripts', 'jupyter')()
  File "/usr/lib/python3/dist-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/lib/python3/dist-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-kernelspec` not found.
```

**Comment by n-riesco** [comment]
`ijavascript` requires `jupyter`: `sudo apt install jupyter` should fix your issue.

**Comment by n-riesco** [comment]
It looks like `jupyter-notebook` doesn't depend on `jupyter-client` any longer. I'll update the documentation to recommend the installation of `jupyter` in Ubuntu,

**Comment by secondl1ght** [comment]
Thanks! I did this and have it working now, I am just starting to learn how to code so do not know what all the error messages mean yet. Appreciate the help!
