### ISSUE TITLE
Hide execution result when code terminated by ;

### ISSUE THREAD

**Issue by wei3erHase** [n-riesco/ijavascript#246]
Every Jupyter cell has an output, no matter if the user decides to have that output or not.
The output is represented by the last line of each cell, even when `;` is used.
Is there a way to avoid automatic outputs? To allow them only when no `;` is used on the last line?

**Comment by n-riesco** [comment]
By default, IJavascript behaves as the Node.js CLI does.

There are a few command flags to customise this behaviour. Probably, not what you're after:
- `--hide-undefined`          do not show undefined results
- `--hide-execution-result`          do not show execution results

There is also the flag `--startup-script=path` (to run a script on kernel startup; path can be a file or a folder), that lets you customise IJavascript behaviour further.

This approach has been used successfully by https://www.npmjs.com/package/magicpatch. See [this comment](https://github.com/n-riesco/ijavascript/issues/244#issuecomment-871188861) for a pointer to the relevant code. If you decide to go this route and you need more help, please, let me know.
