### ISSUE TITLE
Jupyter Lab - iJavascript not working

### ISSUE THREAD

**Issue by macroking** [n-riesco/ijavascript#250]
I am using Juypyter-lab, when I tried to install iJavascript on my Ubuntu OS. I am getting the following message

~/.npm-global/bin/ijsinstall 
Error running `jupyter --version`
Error: Command failed: jupyter --version
/bin/sh: 1: jupyter: not found

Error running `ipython --version`
Error: Command failed: ipython --version
/bin/sh: 1: ipython: not found

**Comment by n-riesco** [comment]
IJavascript requires `jupyter`. Have you run `sudo apt install jupyter` before installing IJavascript?
