### ISSUE TITLE
i dont see any output in jupyter notebook 

### ISSUE THREAD

**Issue by kom-senapati** [n-riesco/ijavascript#254]
I installed ijavascript but its not working its showing in jupyter lab
and i dont see any output in jupyter notebook 
What i should do

**Comment by n-riesco** [comment]
What do you see?
What did you run?
How did you install IJavascript?

**Comment by KOMNOOB** [comment]
by npm install -g ijavascript 
and ijsinstall

I saw kernel not connecting not working

i run 
console.log("hi");

**Comment by KOMNOOB** [comment]
![image](https://user-images.githubusercontent.com/92045934/141407382-6f028b64-c18b-404f-b3e4-8e30d47c23af.png)

**Comment by KOMNOOB** [comment]
![image](https://user-images.githubusercontent.com/92045934/141407565-91cea349-2ed7-4f7b-ab4f-784270e01df9.png)

**Comment by KOMNOOB** [comment]
![image](https://user-images.githubusercontent.com/92045934/141407647-f208a25a-659e-4126-b052-423ac0a72167.png)

**Comment by KOMNOOB** [comment]
![image](https://user-images.githubusercontent.com/92045934/141408016-2217c328-1d49-476d-974c-9de635bcf7ee.png)

**Comment by n-riesco** [comment]
Thank you for all the logs. That helps.

It looks like there was a problem during the installation of ijavascript.

Please, could reinstall ijavascript and see if it prints out any errors?

```
npm uninstall -g ijavascript
npm install -g ijavascript
```

**Comment by KOMNOOB** [comment]
![image](https://user-images.githubusercontent.com/92045934/142634442-53b7e54f-e1c0-4341-9a90-12b089d22976.png)

**Comment by KOMNOOB** [comment]
Tell what to do next

**Comment by n-riesco** [comment]
Oh! That looks like issue #255. The latest release of IJavascript (v2.5.1) should've fixed it.

What do you get when you run `ijsinstall --version`?
