### ISSUE TITLE
Ijavascript kernel will not start on jupyter-desktop

### ISSUE THREAD

**Issue by bryevdv** [n-riesco/ijavascript#259]
* xref: https://github.com/jupyterlab/jupyterlab-desktop/issues/272

Posted the above issue (many details there) on the jupyterlab-desktop repo but perhaps here is a better place to ask. Should this be expected to work?

**Comment by n-riesco** [comment]
Judging by the error message: `FileNotFoundError: [Errno 2] No such file or directory: 'ijskernel'`, it looks like your installation of jupyter-desktop doesn't include `ijskernel` in its `PATH`.

I guess you've used `ijsinstall` to install the kernelspec for  IJavascript. If that's the case, a quick workaround is to install the kernelspec with full paths, like this:

```
ijsinstall --spec-path=full
```

**Comment by bryevdv** [comment]
:pray: This worked for me with jupyter desktop version 3.2.4-3 

Happy to close or leave open for documentation as you prefer

**Comment by n-riesco** [comment]
I should add a troubleshooting section to the README.
I've just opened #260 to keep track of solutions to common problems.
