### ISSUE TITLE
Install ijavascript in Windows without Visual Studio

### ISSUE THREAD

**Issue by martinklein** [n-riesco/ijavascript#269]
Is there any possibility or trick to install ijavascript in Windows 11 without having to install Visual Studio.
I have a working Anaconda environment with a working Jupyter Notebook environment with Qiskit working and of course I have node.js and npm installed and working.

Should not be too complicated to integrate ijavascript into this without Visual Studio ???

Many thanks for your help
Martin Klein

**Comment by dove88** [comment]
@n-riesco 
@martinklein 

Is it possible someone upload Ijavascript folder as metioned in this thread, so that I may copy the folder and install it locally in my machine (windows 10)?
Thank you, it will be great help.

**Comment by n-riesco** [comment]
@dove88 the binaries not only depend on your OS (windows 10), but also the Node.js version.

In fact, if you can use Node.js v14, then you wouldn't need VS code, as `zeromq` provides the binaries.

**Comment by n-riesco** [comment]
@martinklein I'm talking from the top of my head (I'm pretty sure I got the version number right). So... yes, I expect it to work out of the box for Node.js v14.

**Comment by dove88** [comment]
Actually I tried out with node version 14, there was no issue with zermoq installation but even after running ijsinstall, I couldn't find out js_node kernel in my jupyter notebook, thanks
I believe there was problem while running ijsinstall since the installation window just pop up and gone.

**Comment by dove88** [comment]
@n-riesco 

Actually I tried out with node version 14, there was no issue with zermoq installation but even after running ijsinstall, I couldn't find out js_node kernel in my jupyter notebook, thanks
I believe there was problem while running ijsinstall since the installation window just pop up and gone.

**Comment by dove88** [comment]
@n-riesco 
Please ignore my previous comment.
Thank you man, it is working for me, I just forgot to install it globally, just missed -g.
Thank you again.

**Comment by martinklein** [comment]
I cannot install node version 14 in my Anaconda Distribution. Version 14.9.1 was the latest 14 Version - so I tried:
`conda install nodejs=14.9.1`
But that tells me that it does not find such a Version....

**Comment by martinklein** [comment]
Problem solved !
I installed everything outside of Anaconda and finally moved the ijavascript folder into Anaconda.
Everything works fine now.
Many thanks for your help.
