### ISSUE TITLE
No output when using %%javascript magic

### ISSUE THREAD

**Issue by tyler71** [n-riesco/ijavascript#274]
First line was run using the `ipykernel` kernel using `%%javascript` magic. I expect a `Hello World` output.
Second line was run using the `ijavascript` kernel.

![CopyQ xtzjLU](https://user-images.githubusercontent.com/4926565/181292987-e81702f6-a73c-40fe-affd-dbbc73fd61c2.png)

I installed it with the following command in a Dockerfile:

```
RUN npm install -g ijavascript \
 && ijsinstall --install=global --spec-path=full
```

**Comment by lxl0506** [comment]
您好，攀枝花市文广旅局人事科已收到你的邮件！

**Comment by n-riesco** [comment]
My understanding is the `%%javascript` runs your code in the jupyter notebook console (for most browsers, press Command+Option+J (Mac) or Control+Shift+J (Windows, Linux, ChromeOS) to open the console).

You could try and replace `console.log` with `alert` to see what I mean.

**Comment by n-riesco** [comment]
Closing as this isn't an ijavascript-related issue.
