### ISSUE TITLE
import / require statements break vscode code analysis

### ISSUE THREAD

**Issue by mknj** [n-riesco/ijavascript#276]
Do you have any idea why this is happening or where i can report this problem?

The code analysis across cells breaks as soon as i add an `import` or `require` statement to any cell.
* x is reported as unused
* y is any

![vscode_jupyter_js_code_analysis](https://user-images.githubusercontent.com/4385662/201471666-be057619-abdd-4dc3-9e69-54b1562bc44d.gif)

**Comment by n-riesco** [comment]
My untested guess would be that intellisense skips cells that cause execution errors (in this case, the non-existent modules).

If it's still broken with existent modules, I'd report the issue to https://github.com/microsoft/vscode-jupyter/issues .

**Comment by mknj** [comment]
to be continued here https://github.com/microsoft/vscode-jupyter/issues/12019
