### ISSUE TITLE
Jupyter notebook (and Jupyter lab too) gives error when loading d3 library

### ISSUE THREAD

**Issue by deamonpog** [n-riesco/ijavascript#279]
When I install a library such as `lodash` it works well. However it gives me errors when only getting the `d3` package. I have installed it locally ( using `npm install d3` )
Is this behavior due to `d3` being spread over multiple smaller modules?
How would I be able to use `d3` ?
![image](https://user-images.githubusercontent.com/10246255/223017135-238562e4-f608-479b-9621-7441765b9143.png)

**Comment by deamonpog** [comment]
I actually found that it works for older versions such as `d3@5` and `d3@6`.

**Comment by n-riesco** [comment]
The error message is telling us that `require` only works with CJS modules. Unfortunately, `d3` is now only releasing ES modules.

To make matters worse, at them moment `ijavascript` can only import ES modules dynamically (see #210).

I'm closing this issue to keep the conversation on ES modules under #210.
