### ISSUE TITLE
Is it still maintained

### ISSUE THREAD

**Issue by thealidev** [n-riesco/ijavascript#284]
I like to ask if this project is still maintained by developer  
I see last update is at last year

**Comment by n-riesco** [comment]
It is still maintained: bug reports get fixed and user support is provided (via github issues).
But I'm not implementing new features, until the situation with [zeromq](https://www.npmjs.com/package/zeromq) gets resolved, or I find an alternative dependency.

If anyone wants to contribute, I'm not opposed to adding new features. But we all need to be aware that `zeromq` can stop working or it may not provide pre-compiled binaries for your system.

**Comment by thealidev** [comment]
Oh
I get it
Thanks
I am still beginner

**Comment by thealidev** [comment]
Bye

**Comment by n-riesco** [comment]
No worries. If you find any problems using ijavascript, please, don't hesitate to open an issue.
