### ISSUE TITLE
Cant install ijavascript (npm ERR! enoent spawn C:\Windows\system32\cmd.exe ENOENT)

### ISSUE THREAD

**Issue by RalfReddings** [n-riesco/ijavascript#285]
I am very new to node/npm etc. Pardon me, if I am maxing my terms.

I am trying to set up **[ijavascript](https://github.com/n-riesco/ijavascript)** on my system, so that I can take notes of interactive JavaScript code in VSCode (Jupyter Notebook), like I currently can with Python.

I am stuck on actually setting it up, the instructions, [Windows (Official Python Distribution)](https://github.com/n-riesco/ijavascript#windows-official-python-distribution) say:
    
    pip3 install --upgrade pip
    pip3 install jupyter
    npm install -g ijavascript
    ijsinstall
    # Or run: %appdata%\npm\ijsinstall
    
I managed to do `pip3 install --upgrade pip` and `pip3 install jupyter`  but `npm install -g ijavascript` always throws an error:
    
    npm ERR! syscall spawn C:\Windows\system32\cmd.exe
    npm ERR! path C:\Temp\node_modules\zeromq
    npm ERR! errno -4058
    npm ERR! enoent spawn C:\Windows\system32\cmd.exe ENOENT
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent
    
    npm ERR! A complete log of this run can be found in: C:\Users\\AppData\Local\npm-cache\_logs\2023-10-24T23_30_15_508Z-debug-0.log
    C:\Temp                                                                                                                                                                         00:30 Wednesday 25-10-2023 _cnpm install -g ijavascript
    npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    npm ERR! code ENOENT
    npm ERR! syscall spawn C:\Windows\system32\cmd.exe
    npm ERR! path C:\Users\\AppData\Roaming\nvm\v21.1.0\node_modules\ijavascript\node_modules\zeromq
    npm ERR! errno -4058
    npm ERR! enoent spawn C:\Windows\system32\cmd.exe ENOENT
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent
    
    npm ERR! A complete log of this run can be found in: C:\Users\\AppData\Local\npm-cache\_logs\2023-10-24T23_30_54_675Z-debug-0.log
    
I tried it without the global option, `npm install ijavascript`, for a moment a folder is created in working directory but then its deleted. 
I can install other packages with NPM just fine, both globally and locally. I also tried downgrading to an older version of Node, as suggested [here](https://stackoverflow.com/questions/67399785/how-to-solve-npm-install-error-npm-err-code-1),  but it did not help. 

I am on windows 11
Any help would be greatly appreciated!

**Comment by n-riesco** [comment]
If I'm reading the error message correctly, the command prompt `cmd.exe` is missing in your system.

Are you able to open a command prompt? (`Win+R` followed by `cmd.exe`)

If `cmd.exe` is missing, [this link](https://superuser.com/questions/1635048/how-can-i-restore-cmd-exe-command-prompt-if-it-doesnt-exist) may be useful.

**Comment by RalfReddings** [comment]
that did it, thank you THANK YOU!
