### ISSUE TITLE
ijsinstall: not working due to wrong use of ipython --user

### ISSUE THREAD

**Issue by sohang3112** [n-riesco/ijavascript#286]
```console
$ npm install -g ijavascript-await
$ ijsinstall 
Error running `ipython kernelspec install --replace C:\Users\SOHANG~1\AppData\Local\Temp\9828760a66989ad4df1621c6b0a8ff31\javascript --user`
ipython: error: argument --user: expected one argument
```

### Environment / Versions
- `ijavascript-await`: version 5.2.1
- IPython 8.18.1
- Python 3.11.0
- Operating System: Windows 11

**Comment by n-riesco** [comment]
It looks like your installation is missing [`jupyter-client`](https://pypi.org/project/jupyter-client/).

Have you installed `jupyter` in your computer?
What method did you use?

**Comment by sohang3112** [comment]
@n-riesco I installed using `pip install jupyter`. `jupyter-client` is installed on my laptop:

```console
$ pip show jupyter-client
Name: jupyter_client                                                                                              12/13/2023 06:50:59 PMName: jupyter_client
Version: 7.4.8
...
```

**Comment by n-riesco** [comment]
In that case, we need to find out why `ijsinstall` can't run `jupyter`. What happens when you run `jupyter kernelspec list` in the same terminal you run `ijsinstall`?

**Comment by sohang3112** [comment]
> What happens when you run `jupyter kernelspec list` in the same terminal you run `ijsinstall`?

This output shows (since I have installed a few other kernels also):
```console
$ jupyter kernelspec list                                                                                              12/16/2023 07:56:19 PM
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Available kernels:
  dyalog-kernel    C:\Users\SohangChopra\AppData\Roaming\jupyter\kernels\dyalog-kernel
  rust             C:\Users\SohangChopra\AppData\Roaming\jupyter\kernels\rust
  python3          C:\Users\SohangChopra\AppData\Local\Programs\Python\Python311\share\jupyter\kernels\python3
  forth            C:\ProgramData\jupyter\kernels\forth
  kernelspec       C:\ProgramData\jupyter\kernels\kernelspec
```

**Comment by n-riesco** [comment]
Try running 'ijsinstall` in the same terminal where `jupyter kernelspec` is working and see if you get the same error message.

Otherwise, I need to find a windows machine to try and reproduce the problem.

**Comment by sohang3112** [comment]
Closing this issue, as I'm not using ijavascript nowadays
