### ISSUE TITLE
When I use npm to install the ijavascript kernel and switch to it in the Jupyter environment in VS Code, then switch back to the Python environment, the code suggestions are still those from the JS environment. How can I fix this?

### ISSUE THREAD

**Issue by jaon1234** [n-riesco/ijavascript#291]
![image](https://github.com/n-riesco/ijavascript/assets/13372894/c6f7d8e2-fc30-4970-9ebc-6fd35b3d768e)

**Comment by n-riesco** [comment]
This seems a VSCode issue. Please, report it at https://github.com/microsoft/vscode/issues .
