### ISSUE TITLE
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  

### ISSUE THREAD

**Issue by woodgreat** [n-riesco/ijavascript#292]
npm install -g ijavascript
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

when I install our module ,I meet this .how to solve it .thanks

**Comment by woodgreat** [comment]
and ,my uuid version is 10
---------------------------------------
 npm list -g --depth 0
C:\Program Files\nodejs -> .\
+-- corepack@0.24.0
+-- ijavascript@5.2.1
+-- npm@10.8.1
+-- typescript@5.4.5
`-- uuid@10.0.0

**Comment by n-riesco** [comment]
Thank you for taking the time to report this issue. I've labelled this issue as a question, so that other iJavascript users are aware of my plans to address it. See https://github.com/n-riesco/ijavascript/pull/293#issuecomment-2208578227 .

**Comment by woodgreat** [comment]
gotta
