### ISSUE TITLE
Error installing on Mac

### ISSUE THREAD

**Issue by jtfogarty** [n-riesco/ijavascript#34]
MacBooks-MBP:dat macbookpro$ sudo npm install -g ijavascript
Password:
-
> zmq@2.11.1 install /usr/local/lib/node_modules/ijavascript/node_modules/zmq
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/macbookpro/.node-gyp/0.12.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ijavascript/node_modules/zmq/.node-gyp"
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ijavascript/node_modules/zmq
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ijavascript"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.11.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/macbookpro/logstash-1.5.1/dat/npm-debug.log

**Comment by jtfogarty** [comment]
info from log

606 verbose unlock done using /Users/macbookpro/.npm/_locks/ijavascript-78c9ad2e25a7cf1f.lock for /usr/local/lib/node_modules/ijavascript
607 verbose stack Error: zmq@2.11.1 install: `node-gyp rebuild`
607 verbose stack Exit status 1
607 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
607 verbose stack     at EventEmitter.emit (events.js:110:17)
607 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
607 verbose stack     at ChildProcess.emit (events.js:110:17)
607 verbose stack     at maybeClose (child_process.js:1015:16)
607 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
608 verbose pkgid zmq@2.11.1
609 verbose cwd /Users/macbookpro/logstash-1.5.1/dat
610 error Darwin 14.3.0
611 error argv "node" "/usr/local/bin/npm" "install" "-g" "ijavascript"
612 error node v0.12.4
613 error npm  v2.10.1
614 error code ELIFECYCLE
615 error zmq@2.11.1 install: `node-gyp rebuild`
615 error Exit status 1
616 error Failed at the zmq@2.11.1 install script 'node-gyp rebuild'.
616 error This is most likely a problem with the zmq package,
616 error not with npm itself.
616 error Tell the author that this fails on your system:
616 error     node-gyp rebuild
616 error You can get their info via:
616 error     npm owner ls zmq
616 error There is likely additional logging output above.
617 verbose exit [ 1, true ]
618 verbose unbuild lib/node_modules/ijavascript/node_modules/zmq
619 info preuninstall zmq@2.11.1
620 info uninstall zmq@2.11.1
621 verbose unbuild rmStuff zmq@2.11.1 from /usr/local/lib/node_modules
622 verbose unbuild rmStuff in /usr/local/lib/node_modules/ijavascript/node_modules
623 info postuninstall zmq@2.11.1
624 silly gentlyRm /usr/local/lib/node_modules/ijavascript/node_modules/zmq is being purged from base /usr/local
625 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ijavascript/node_modules/zmq
626 silly vacuum-fs purging /usr/local/lib/node_modules/ijavascript/node_modules/zmq
627 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules/ijavascript/node_modules
628 verbose unbuild lib/node_modules/ijavascript
629 info preuninstall ijavascript@5.0.3
630 info uninstall ijavascript@5.0.3
631 verbose unbuild rmStuff ijavascript@5.0.3 from /usr/local/lib/node_modules
632 silly gentlyRm /usr/local/bin/ijs is being gently removed
633 silly gentlyRm verifying /usr/local is an npm working directory
634 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
635 silly gentlyRm deletion target /usr/local/bin/ijs is under /usr/local
636 verbose gentlyRm vacuuming from /usr/local/bin/ijs up to /usr/local
637 info postuninstall ijavascript@5.0.3
638 silly gentlyRm /usr/local/lib/node_modules/ijavascript is being purged from base /usr/local
639 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ijavascript
640 silly vacuum-fs purging /usr/local/lib/node_modules/ijavascript
641 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules

**Comment by rgbkrk** [comment]
> `pkg-config: command not found`

If you're using `brew`, you'll need to run `brew install pkg-config`

**Comment by n-riesco** [comment]
I will update the install instructions for Mac.

PS: Thanks Kyle.

**Comment by rgbkrk** [comment]
Thanks for updating the instructions!
