### ISSUE TITLE
Information - Ño Bug

### ISSUE THREAD

**Issue by MortalCatalyst** [n-riesco/ijavascript#37]
Just a question to further understand implementation details and future opportunities.

First Thank you for creating and driving this project it's much appreciated. 

The ipython project can handle only a dynamic kernel can't it? So nothing that requires compilation Babel/TypeScript etc would not work would they?

**Comment by n-riesco** [comment]
If the question is whether it would be possible to write a kernel for Babel or Typescript. The answer is yes, although I imagine it requires compiling each cell into Javascript and running on `Node.js`. This is from a quick search on https://www.npmjs.com : 

https://www.npmjs.com/package/babel-repl
https://www.npmjs.com/package/tsun

If you want to run Coffescript, Babel or Typescript from IJavascript then you need to install the necessary `npm` packages and `require` them from within your code. For example, if you want to run a piece of Coffescript code, you could do:

```js
var cs = require("coffee-script");
cs.eval(
    "if Math.random() >= 0.5 then 'head' else 'tail'"
);
```

Does this answer your question?

**Comment by MortalCatalyst** [comment]
Yes thank you. I was interested in being able to try latest JavaScript babel features and  TypeScript
