### ISSUE TITLE
Need ability to install kernel spec globally.

### ISSUE THREAD

**Issue by bigzachattack** [n-riesco/ijavascript#38]
Currently `--ijs-install-kernel` will always install into the user's IPython/Jupyter profile.   

IPython/Jupyter also supports global install path of `/usr/local/share/jupyter/kernels`.  By default IPython `install-self` installs globally and when into the user's profile when the `--user` option is added.

It would be nice for IJavascript to mirror this behavior.

**Comment by n-riesco** [comment]
Just a few quick thoughts:
- I'd like to stay backwards-compatible and keep the behaviour of `--ijs-install-kernel`
- currently, `ijs` only parses command flags starting with `--ijs-`, any other command flags and arguments are passed onto `ipython`
- it would be possible to make `ijs` smarter and parse commands like `ijs install-self --user`, but I don't think the effort would be justified when adding another flag like `--ijs-install-global-kernel` would do the job.

Would a flag like `--ijs-install-global-kernel` be enough for your needs?

**Comment by bigzachattack** [comment]
That makes sense.

`--ijs-install-global-kernel` works just as well.

**Comment by rgbkrk** [comment]
There is a [`jupyter-paths`](https://github.com/nteract/jupyter-paths) node package for resolving these paths as well by the way.

**Comment by n-riesco** [comment]
@rgbkrk Is there anything like that for IPython? I need a cross-platform way to determine the global location of the kernel specs that works with IPython.

**Comment by rgbkrk** [comment]
I think we could add the pathing support for detecting it on old installations as well. I did this a bit ago and kind of hated straddling all-in-one, hoping to make an `ipython-paths` package and then just using both to detect which to use.
