### ISSUE TITLE
Custom html/css?

### ISSUE THREAD

**Issue by jakubholynet** [n-riesco/ijavascript#40]
I am new to Jupyter notebooks and cannot figure out how to include custom HTML in a notebook. Namely I would like to add some CSS styles to use later on (I am successfully using ijavascript with [RISE](https://github.com/damianavila/RISE) to create live slide shows and want to center things etc.).

I can google out [some solutions](http://stackoverflow.com/questions/18024769/adding-custom-styled-paragraphs-in-markdown-cells) but they apply to ipython (relying on executing python code). Some suggest using `<style>` in a markdown cell but that doesn't seem to work for me.

Could you please extend the documentation with tips in this regard?

Thanks a lot!

**Comment by n-riesco** [comment]
To help me understand, please, could you give me an example of what you're trying to do?

Have you seen [this documentation](http://n-riesco.github.io/ijavascript/doc/graphics.ipynb.html)? It includes an example to inject HTML into an output cell.

**Comment by n-riesco** [comment]
Not sure whether this may help you: a kernel spec may include `custom.css` and `custom.js`. See [IPEP25](https://github.com/ipython/ipython/wiki/IPEP-25%3A-Registry-of-installed-kernels).

**Comment by jakubholynet** [comment]
Thanks for the quick response!

I don't know how it is possible but I have overlooked the documentation. I guess the `$$html$$` could perhaps work though CSS styles should be inside `<head>`, which this doesn't enable.

What I am trying to achieve: I have [this notebook](https://github.com/jakubholynet/talks/blob/gh-pages/talk-fp-in-js-2015-v2-iterate_conf/Functional%20Programming%20in%20JavaScript%20-%20Experiences.ipynb) that I use with RISE to produce live presentation slides. I would like to center the 2nd line, i.e. "Jakub Holý - Iterate conference 8/2015". So I want to have either

    .my-centered { text-align: center }

    // And later, on the slide/cell:
    <p class="my-centered">Jakub Holý - Iterate conference 8/2015</p>

(using a class rather then style so that I can use it on multiple elements) or just this

    .text_cell_render p  { text-align: center }

The question is where to put it.

Regarding `custom.(css|js)`, I think those would only be useful if they could be in the notebook directory, i.e. for that notebook, not all.

Thank you!

**Comment by n-riesco** [comment]
This should do the trick using IJavascript:
```js
$$html$$ = '<script>document.styleSheets[0].insertRule(".rendered_html .my-centered { text-align: center; }", 0);</script>';
```
But  I would also ask this question on the [Jupyter mailing](https://groups.google.com/forum/#!forum/jupyter) list. There may be a recommended way to add a `custom.css` to a notebook.

**Comment by n-riesco** [comment]
This message from the mailing list may be relevant:

https://groups.google.com/d/msg/jupyter/Hak-Xjwro3k/_NznabngCwAJ

**Comment by n-riesco** [comment]
@jakubholynet I'm closing this issue. If the comments above don't help, please, feel free to reopen this issue.

**Comment by jakubholynet** [comment]
Thank you!
