### ISSUE TITLE
CoffeeScript

### ISSUE THREAD

**Issue by terraqout** [n-riesco/ijavascript#42]
Hello, everyone, thank you for your work. Just found your plugin and happy about that.
And here is a question what need to be implemented to port this and use it with coffeescript binary?

**Comment by n-riesco** [comment]
@kebot proposed a quick hack in https://github.com/n-riesco/nel/issues/1

In the same issue, I wrote an outline of what's required to convert IJavascript into a CoffeeScript kernel. It's doable, and I would like to help, but, right now, I wouldn't want to take the lead of such a project.

**Comment by terraqout** [comment]
@n-riesco Thank you, for links

**Comment by n-riesco** [comment]
To get the ball rolling, here's the quick hack to provide a CoffeeScript kernel:

https://github.com/n-riesco/jp-coffeescript

**Comment by terraqout** [comment]
great!
