### ISSUE TITLE
Displaying function body 

### ISSUE THREAD

**Issue by terraqout** [n-riesco/ijavascript#44]
I recently switched to your kernel from notablemind's one. 
And what I miss for is displaying body of function. I think this is by design but why?

```
jupyter-nodejs:
> a = -> a
> a
function a ( ) {
return a;
}
```
and not just [Function a] which is more expected by design of javascript, but meaningless a bit too.

This is quite helpful when you write something functional, composed from small pieces.

**Comment by n-riesco** [comment]
It is how `util.inspect` outputs a function. You can get the other output by calling `.toString()` instead, e.g.:

In[1]: a = -> a
Out[1]: [Function]
In[2]: a.toString()
Out[2]: 'function () {\n  return a;\n}'

**Comment by terraqout** [comment]
So can I add to iJavascript automatically toString application if inspect return [Function ***] ?

**Comment by n-riesco** [comment]
It's more complicated than that. What output would you like for `{a: -> a}`?

**Comment by terraqout** [comment]
Plain js would be preferred.
