### ISSUE TITLE
Autocomplete: own properties first

### ISSUE THREAD

**Issue by terraqout** [n-riesco/ijavascript#45]
Hello again, I want to implement this feature:
When you ask kernel for suggestion, it show's own properties of prototype first and only after all generic one's like toString, etc.
Maybe just move lower Object properties.

This is frustrating when you didn't remember name of "do that stuff" in module having only that one function and running through all this generics.

**Comment by n-riesco** [comment]
The current order is:
1. Property names of the object
2. Property names of the [prototype] chain 
3. Javascript keywords

If I understand correctly the order you are asking for is:
1. Property names of the [prototype] chain 
2. Property names of the object
3. Javascript keywords

Is this what you mean?

**Comment by terraqout** [comment]
Now first ones are global properties started with double underscore like:
__define*, __lookup*
After that own properties of object (they should be first).
And after that object Object properties.

**Comment by n-riesco** [comment]
Oh! This is my bad. I added a .sort() at the wrong place. I will fix it.
