### ISSUE TITLE
error executing ijs

### ISSUE THREAD

**Issue by Qtrain** [n-riesco/ijavascript#48]
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/usr/local/lib/node_modules/ijavascript/spec/javascript/kernel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at installKernelAsync (/usr/local/lib/node_modules/ijavascript/bin/ijavascript.js:287:8)
    at /usr/local/lib/node_modules/ijavascript/bin/ijavascript.js:120:5
    at /usr/local/lib/node_modules/ijavascript/bin/ijavascript.js:236:13
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)

**Comment by n-riesco** [comment]
Thanks for reporting this issue. I've tried to reproduce the problem on an Ubuntu 14.04 and I can't. Please, can you post the steps to reproduce it?
I'd like to undertand why `ijs` can create the file `kernel.json` in folder `/usr/local/lib/node_modules/ijavascript/spec/javascript/`.

**Comment by Qtrain** [comment]
Sry. Actually using OSX which might be the problem.  I will try on an Ubuntu distro and report back.

**Comment by n-riesco** [comment]
This is issue has made realise that I should use a temporary folder to create the kernel spec folder for Jupyter.

I'm very surprised no other OSX users have reported this issue before.

**Comment by Qtrain** [comment]
Cool.  Thx for looking into this.  I'm really interested in using this.  Pls let me know if you come up with a new install for OSX.

**Comment by n-riesco** [comment]
I will some time this week.

**Comment by n-riesco** [comment]
In the meantime, installaling ijavascript locally should work on OSX:

```
$ npm install ijavascript
$ node_modules/.bin/ijs
```

**Comment by n-riesco** [comment]
@Qtrain Please, reopen this issue if the problem is still present in OSX. Thanks again.
