### ISSUE TITLE
Logo Thoughts

### ISSUE THREAD

**Issue by rgbkrk** [n-riesco/ijavascript#56]
Hey @n-riesco, I know I'm the one that pestered about a logo sometime ago. After having used this for a while, I'd love to see the standard node logo to show similar to how IPython just shows Python's logo:

![image](https://cloud.githubusercontent.com/assets/836375/12517422/2b5f3e50-c0f8-11e5-87c6-552715398b76.png)

For ijavascript (which is definitely node and not browser javascript), the logo should be the node logo (this one comes from the nodejs github org):

![node logo](https://avatars1.githubusercontent.com/u/9950313?v=3&s=200)

Scala, R, and many other kernels all use the logo of their respective language. I do think it's ok for the Babel kernel to use:

![babel logo](https://avatars2.githubusercontent.com/u/9637642?v=3&s=200)

**Comment by rgbkrk** [comment]
Current header:

![screenshot 2016-01-22 11 14 05](https://cloud.githubusercontent.com/assets/836375/12517587/0c3a7584-c0f9-11e5-90d5-6d9e2b7f5a93.png)

Proposed header:

![screenshot 2016-01-22 11 14 54](https://cloud.githubusercontent.com/assets/836375/12517607/253b9b58-c0f9-11e5-9404-0c4770902efc.png)

**Comment by n-riesco** [comment]
I imagine that as long it is clear that the logos identify the language rather than the kernel, it will be OK.

I will look for their licenses.

**Comment by rgbkrk** [comment]
Here's the [Logo page](https://nodejs.org/en/about/resources/) which references the [Trademark Guidelines](https://nodejs.org/static/documents/trademark-policy.pdf)

The particularly relevant bits:

> Q: Can I use the Node.js marks? A: Yes, in accordance with these guidelines.

In the project README we probably have to include:

> Node.js is a trademark of Joyent, Inc. and is used with its permission. We are not endorsed by or
affiliated with Joyent.

We also can not sell items using the Node.js logo.

This is open source software designed to help people interact with node, learn, do research, and develop software. It would be pretty crazy for us to run into problems here.

**Comment by rgbkrk** [comment]
If you're ok with it, I'm happy to submit a PR updating the README and the bundled logo.

**Comment by rgbkrk** [comment]
By the way, I don't mean to overwrite the main IJavascript logo, only the language icon shown in the corner.

**Comment by n-riesco** [comment]
OK.

You'd need to edit the logo filename here:

   https://github.com/n-riesco/ijavascript/blob/master/bin/ijavascript.js#L297

and here:

 https://github.com/n-riesco/ijavascript/blob/master/bin/ijavascript.js#L299

I would also add a LICENSE file to the images folder listing the filenames of Joyent's files and providing a link to Joyent's trademark guidelines.

**Comment by rgbkrk** [comment]
Sorry that took me a bit to get done. It's in #57.
