### ISSUE TITLE
Update documentation for asynchronous output

### ISSUE THREAD

**Issue by n-riesco** [n-riesco/ijavascript#64]
The documentation in http://n-riesco.github.io/ijavascript/doc/async.ipynb.html needs updating.

See #58

**Comment by neil-s** [comment]
Sorry for the radio silence, and thanks for your tips in #58 , the IIFE worked perfectly. Besides updating the documentation for users to do this on the application code level, would it be worth investigating doing it at a system level? Wrapping each cell in an IIFE so users could use console like they normally would?

**Comment by n-riesco** [comment]
Wrapping each cell would have the undesirable effect of making any variable or function declarations in one cell invisible to other cells.

**Comment by neil-s** [comment]
Yeah, I'm still wrapping my head around JS variable scoping, but that's what I thought. Never mind.

**Comment by n-riesco** [comment]
No worries. One of the reasons why the latest release is still a beta is so that we can play the new changes and find out what are the most convenient patterns.
