### ISSUE TITLE
Update Install Instructions for OS X

### ISSUE THREAD

**Issue by xaranke** [n-riesco/ijavascript#65]
Thanks for the great work on this kernel. 

There are just a couple small tweaks required to make this run on OS X:
1. Specify that Python version 2 is required and not version 3 since `gyp` and by extension `node-gyp` require Python version 2.
2. Update last line with `pip` to `pip install -U pyzmq jupyter`.

Also, it would be safe to move the OS X instructions to the README since I have verified this on 2 computers now. Let me know if you would like me to create a Pull Request for this issue.

Also, just for diagnostic purposes:
1. `ijs --version` -> `5.0.11-beta.0`
2. `npm --version` -> `3.7.3`
3. `ipython --version` -> `4.1.2`
4. `sw_vers -productVersion` -> `10.11.3`

Best,
Kshitij

**Comment by n-riesco** [comment]
Thanks for all this info. It comes at a perfect time, because I'm in the process of updating the documentation for v5.0.11.

**Comment by xaranke** [comment]
Perfect, thanks!

**Comment by n-riesco** [comment]
I believe 881092afb617624250440b8156ffa1d1bdf6a08e fixes this issue (just released as IJavascript@5.0.11).
