### ISSUE TITLE
require/import packages

### ISSUE THREAD

**Issue by Simobain** [n-riesco/ijavascript#69]
EDIT no more problem : TO CLOSE

**Comment by n-riesco** [comment]
On 01/06/16 08:21, Simobain wrote:
> Where should I install packages to be accessible by my nodejs kernel ? I don't see any node_modules folder.

Same locations you would use to make them accessible from a nodejs session. If the package is accessible from node, it'll be accessible from IJavascript.

For example, if you want to install the package `uuid` locally to your user:

```
$ cd
$ npm install uuid
$ node
> var uuid = require('uuid');
> uuid.v4();
'110ec58a-a0f2-4ac4-8393-c866d813b8d1'
```

Alternatively, you can install the package globally:

```
$ sudo npm install -g uuid
$ node
> var uuid = require('uuid');
> uuid.v4();
'110ec58a-a0f2-4ac4-8393-c866d813b8d1'
```

If the above doesn't work for you, please, post what OS you're using and the steps you follow to install the package and run IJavascript.
