### ISSUE TITLE
Promises and async/await

### ISSUE THREAD

**Issue by jmatsushita** [n-riesco/ijavascript#73]
This might be more for `jp-babel` but it would be great (and maybe avoid some of the IIFE boilerplate?) to have async/await style asynchronous code. I don't know if it could help avoid having to declare `$$.async();` or the `$$` scope passing?

Maybe an intermediary step would be to wrap the whole notebook in a Promise and allow cells to contain promises?

**Comment by n-riesco** [comment]
On 25/07/16 08:22, Jun Matsushita wrote:
> Maybe an intermediary step would be to wrap the whole notebook in a Promise and allow cells to contain promises?

Could you give me an example of how this would be used?

**Comment by jmatsushita** [comment]
Sure thing! Here's one: https://github.com/iilab/notebooks/blob/master/Promises.ipynb

I use IJavascript and node 6.3. Some interesting things happen there though:
 - This doens't work when executing the whole notebook. Only if I execute the cells individually.
 - There are 2 output cells. (!)
 - This (*somewhat*) hangs the Kernel and I can't start other notebooks which are stuck `Kernel starting. Please wait...`. Waiting a bit then works and the new notebooks become responsive irrespective of what happens in the Promises notebook.

I've also added a little example of what the `async` version would look like.

**Comment by jmatsushita** [comment]
I could make some async work with a patched jp-babel!
 https://github.com/iilab/notebooks/blob/master/Promises-Babel-Async.ipynb

**Comment by n-riesco** [comment]
The first thing I have to say is that I haven't updated `jp-babel` yet. `jp-babel` doesn't understand the new `$$`.

I'll have a look and see if I can put something together for `jp-babel` (and `jp-coffeescript`).

**Comment by n-riesco** [comment]
@jmatsushita Updating `jp-babel` is not a minor change. It'll have to wait until I refactor the code in `IJavascript` so that it can be reused by `jp-babel` and `jp-coffeescript`.

3 out of the 4 examples in your notebook can be run in `IJavascript`. Here's how:

### Cell 1
```javascript
// Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
'use strict';

var rp = require('request-promise');

{
    let $$ = global.$$;
    $$.async();
    rp('https://github.com/status').then(r => $$.sendResult(r));
}
```

### Cell 2

```javascript
// Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
'use strict';

var rp = require('request-promise');

{
    let console = global.console;
    let $$ = global.$$;
    $$.async();
    rp('https://github.com/status').then(r => console.log(r)).then($$.done); // invoke $$.done when no results are returned
}
```

### Cell 3

```javascript
// Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
'use strict';

var sleep = require('sleep-promise');

{
    let console = global.console;
    let $$ = global.$$;
    $$.async();
    console.log('Hello, World!');
    sleep(1000).then(r => $$.text('Bye!'));
}
```

**Comment by pkese** [comment]
Node 6 should be able to support async/await without babel if the kernel would be run using --harmony flag.

Does anyone know how to pass command line argument to kernel?

**Comment by n-riesco** [comment]
@pkese There is no option to do that. A quick workaround would be to edit the `nel` package; more specifically, [here](https://github.com/n-riesco/nel/blob/master/lib/nel.js#L200-L205).

**Comment by pkese** [comment]
Thanks @n-riesco -- I managed to find that same line of code myself (although it took me somewhat more time than you ;-) ).

You rock!
