### ISSUE TITLE
How to install in JupyterHub

### ISSUE THREAD

**Issue by nevi-me** [n-riesco/ijavascript#74]
I got `ijs` running on a standalone Jupyter notebook, and `jupyter kernelspec list` shows the kernel in my list, but JupyterHub doesn't show it. Is there anyone who's managed to get this working?

Thanks

**Comment by nevi-me** [comment]
Found the solution, the kernel was installed in `~/.local/` so I used `jupyter kernelspec install <dir>`, and now it's working.

**Comment by n-riesco** [comment]
This may be a bug in IJavascript. When I updated `ijs` to prefer `jupyter` over `ipython`, I forgot to update the install function (that is still using `ipython kernelspec install --replace /path/to/kernel/dir`).

It's surprising, though, that `jupyter kernelspec list` sees that kernel, JupyterHub doesn't.

I will open an issue to fix the install function.
