### ISSUE TITLE
[question] terminal support

### ISSUE THREAD

**Issue by sibelius** [n-riesco/ijavascript#79]
is this support terminal as well? like ipython?

``` js
$ ipython
In [1]: 
```

is there any solution that is as close to ipython on terminal for nodejs?

best

**Comment by n-riesco** [comment]
This should work:
```
jupyter console --kernel=javascript
```

provided IJavascript's kernelspec has already been installed. If it hasn't, then run:
```
ijs --ijs-install=local
```

**Comment by shreevatsa** [comment]
@n-riesco Could you add this to the documentation?

(Also perhaps a comparison between this and [jupyter-nodejs](https://github.com/notablemind/jupyter-nodejs/blob/f9f44263d024556870d83a3b813d52fdce74eb88/Readme.md#installation), whose Readme page more prominently shows the example of the terminal usecase.)
