### ISSUE TITLE
Support Python 3.5.2

### ISSUE THREAD

**Issue by periscuelo** [n-riesco/ijavascript#83]
Congratulations for the Kernel and thank you very much.
How can i use it with python 3.5.2?

Thanks.

**Comment by rgbkrk** [comment]
For building the kernel/zmq? You can still use Python3. Python2 is only required at install time, at least until we have prebuilds of zmq available.

**Comment by periscuelo** [comment]
Are you kidding me. I have to install python 2 just to be able to install the package and then I remove it? I'm a windows user. Just install ijs, remove python 2 and be happy?

**Comment by rgbkrk** [comment]
Yeah, sadly the `node-gyp` story is not that great on Windows.

However, [Microsoft has a nice recent solution for you](https://github.com/nodejs/node-gyp#installation)! It would be great to know if it works for you. Run

```
npm install --global --production windows-build-tools
``` 

from an elevated PowerShell or CMD (run as Administrator).

**Comment by periscuelo** [comment]
Oh yeah, sorry for the lack of attention. I skipped that part and was killing myself doing everything by hand, was much more difficult. I'll try this option that was just above the he was reading and see if works. But I go to sleep and leave it running. Thank you so much. I'll be back here to warn you if that works.

**Comment by periscuelo** [comment]
@rgbkrk yes ijavascript can be installed. Yes run jupyter with javascript kernel.
But [I 05:28:27.172 NotebookApp] Kernel started: abd4bd60-c46f-4fd9-924a-6282f4fa66b8
[I 05:28:30.179 NotebookApp] KernelRestarter: restarting kernel (1/5)
[I 05:28:33.375 NotebookApp] KernelRestarter: restarting kernel (2/5)
[I 05:28:36.551 NotebookApp] KernelRestarter: restarting kernel (3/5)
[W 05:28:37.256 NotebookApp] Timeout waiting for kernel_info reply from abd4bd60-c46f-4fd9-924a-6282f4fa66b8
[I 05:28:39.755 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel abd4bd60-c46f-4fd9-924a-6282f4fa66b8 restarted
[W 05:28:42.947 NotebookApp] KernelRestarter: restart failed

**Comment by periscuelo** [comment]
About the kernel problem have another issue.
[https://github.com/n-riesco/ijavascript/issues/78](https://github.com/n-riesco/ijavascript/issues/78)

Thanks for help me.

**Comment by n-riesco** [comment]
I'm looking into offering the possibility of using `zmq-prebuilt` (this should remove the requirement for Python 2.7 to install zmq).

**Comment by n-riesco** [comment]
Fixed in the latest release IJavascript@5.0.15
