### ISSUE TITLE
Outputting graphics to the notebook?

### ISSUE THREAD

**Issue by mhkeller** [n-riesco/ijavascript#9]
I'm currently working on getting this running on os x — having trouble installing zeromq — so I can't test directly but the project looks really interesting. One of the things I would use it for is to output graphs to the notebook through d3 or some other charting library. Since those systems are usually based on targeting specific dom elements, how would you get a graph to show up inline, for example, similar to how ipython notebook displays ggplot2 graphs?

**Comment by n-riesco** [comment]
I don't have access to any OS X machine, but I've been told [homebrew](https://github.com/Homebrew/homebrew) may help with the install of zeromq (please, let me know what works for you and I will add some instructions to the documentation).

I haven't thought through all the details for embedding charts. A quick'n'dirty('n'untested) fix to get `d3` outputs would be to update `formatResult` in `sm_server.js` so that it outputs the svg produced by `d3`.

I would like to come up with a general scheme (but I need to experiment more and see what works best).

**Comment by mhkeller** [comment]
`brew install` worked — thanks for the suggestion. If I'm understanding you right, `formatResult` would require a function that returns svg? Usually the way graphs are constructed are through appending dom elements (either svg or html if the user wants). Here's an html bar chart for example

````js
d3.select('#container')
    .data([{height: 20}, height: 50]).enter()
    .append('div')
    .style('height', function(d){ return d.height + 'px' })
````

One way it could work is if user appends the graph to a non-visible element (named after some convention). To display it, they call a function on the dom selection like so `ijs.print(document.getElementById('container')), which would return the html / svg of that element. The syntax can be better by supporting d3 or jquery selections if those libraries are present.

Alternatively, the `.print` function could convert to canvas and you get a png back. Support might not be universal though. 

Either way, it seems there needs to be a function that returns what the user has made? As a first draft, you could require users inline style everything, but supporting stylesheets is another conundrum.

**Comment by n-riesco** [comment]
On 16/03/15 14:41, Michael Keller wrote:
> If I'm understanding you right, |formatResult| would require a function that returns svg?

`formatResult` is a function that receives the result of evaluating a javascript cell from the notebook. It returns an object that tells the notebook what the MIME representation is, e.g.

{
    mime: {
        "text/plain": "'Hello, World!'",
        "text/html":  "<pre>'Hello, World!'</pre>",
    },
}

I'm hoping `formatResult` can use "text/html" to return the SVG generated using d3 (perhaps using jsdom?).

If this option doesn't work, there are other possibilities: as you suggest, a PNG could be returned as an "image/png".

As you see, I'm yet to think this through.

I will use this github issue to track any progress.

**Comment by mhkeller** [comment]
Here's an example a strategy: http://eng.wealthfront.com/2011/12/converting-dynamic-svg-to-png-with.html & https://gist.github.com/mattbaker/1509145

The dependency on imagemagick and librsvg (especially given that you have to install them in a specific order) isn't great. I'll see how well svg crowbar works with jsdom (currenly only chrome-compliant) https://github.com/NYTimes/svg-crowbar

**Comment by n-riesco** [comment]
I've looked into this issue a bit further.

First problem, the latest version of `jsdom` is incompatible with `node.js`. It is possible to use version 3.1.2 (but it's unmaintained):

```
npm install jsdom@3.1.2
```

Here's an example to produce a simple SVG using `d3` and `jsdom@3.1.2`:

```javascript
var d3 = require("d3")
var jsdom = require("jsdom")
var document = jsdom.jsdom();

var svg = d3.select(document.body).append("svg").attr("width", 100).attr("height", 100);
svg.append("rect").attr("x", 10).attr("y", 10).attr("width", 80).attr("height", 80).style("fill", "orange");

console.log(document.body.innerHTML); // Output: <svg width="100" height="100"><rect x="10" y="10" width="80" height="80" style="fill: orange;"></rect></svg>
```

I need to check whether more complex `d3` graphs work without embedding `d3.js`.

**Comment by n-riesco** [comment]
The latest commit 086140e58450960aa9a6330e0090e306f72f9c7a implements the magic `%html`, a quick hack that will allow to output SVG images (or HTML).

I haven't released this commit to `npm` yet. To install it in your machine, you'll have to clone the git repository:

```
git clone https://github.com/n-riesco/ijavascript.git
npm install ./ijavascript
```
An example of usage:

```
In[1]: %html "<svg width='100' height='100'><rect x='10' y='10' width='80' height='80' style='fill: orange;`></rect></svg>"
```

or:

```
In[1]: var svg = "<svg width='100' height='100'><rect x='10' y='10' width='80' height='80' style='fill: orange;`></rect></svg>";
Out[1]: undefined
In[2]: %html svg
```

Note that, since a magic is not a valid Javascript expression, the following won't work:

```
In[1]: var svg = "<svg width='100' height='100'><rect x='10' y='10' width='80' height='80' style='fill: orange;`></rect></svg>"; %html svg
```

I need more to time to come up with a more convenient alternative (I've updated the TODO list in [README.md](README.md) so that I won't forget).

**Comment by mhkeller** [comment]
That's great! 

In order to make the usage as seemless as possible, there could be a small wrapper library that users would require that grabs the innerHTML and returns it as a string 

````
var svg_string = extractSvg(d3.select('#svg1'))
%html svg_string
````

**Comment by n-riesco** [comment]
Alternative idea using a global variable:

```
In[1]: var svg = "<svg><rect width='80' height='80' style='fill: orange;`></rect></svg>"
Out[1]: undefined
In[2]: global.$$mime$$ = svg
Out[2]: (orange square)
```

**Comment by mhkeller** [comment]
Nice, I'll test it out this evening and put together a simple svgToString helper. The `%html` usage seems like the easier one to me purely because it's less verbose. But since it's not valid js, I could see that being a downside. Maybe there's a helper function that could accomplish the same thing and take advantage of the global mime convention.

**Comment by n-riesco** [comment]
Yes, I see it is verbose, even in the cases when it's possible to drop `global`:

```javascript
$$mime$$ = {"text/html": svg}
```

A possibility would be to define more globals, e.g. `global.$$html$$`; one for each MIME type supported by the notebook. Then, something like this would be possible:

```javascript
$$html$$ = svg
```

**Comment by n-riesco** [comment]
I've implemented `$$html$$` in the latest commit 2eedf424815573162a8142e8eb1253aea53f4c7b.

**Comment by mhkeller** [comment]
After pulling the latest and running the above lines, it outputs the `svg` but not the contents. 
![screen shot 2015-03-20 at 20 15 53 pm](https://cloud.githubusercontent.com/assets/498744/6762831/f7ded024-cf3d-11e4-8bd1-3814718f7a7c.png)
![screen shot 2015-03-20 at 20 14 33 pm](https://cloud.githubusercontent.com/assets/498744/6762832/f7e1dbde-cf3d-11e4-950b-4ece90d30b5b.png)

**Comment by n-riesco** [comment]
What version of IPython are you using?

```
ipython notebook --version
```

**Comment by n-riesco** [comment]
There is a syntax error in all the SVG samples I've posted here; for some reason, the last single-quote ('), see the `style` attribute, has been replaced with a back tick (`).

I will correct the samples in all the posts, so that no one else stumbles with this problem.

I've checked it works with IPython 1.2.1 and 3.0.0.

**Comment by n-riesco** [comment]
Here's an example for outputting a PNG image:

```javascript
var fs = require("fs");
var png = fs.readFileSync("image.png");
$$mime$$ = {"image/png": png.toString("base64")};
```

**Comment by mhkeller** [comment]
I might have forgotten to install the NodeJS compatible version of jsdom, let me tinker with it tonight and test some more.

**Comment by mhkeller** [comment]
Sorry for the delay. I've been playing around with it trying to get it to work but this is what I'm getting
![screen shot 2015-04-14 at 21 39 12 pm](https://cloud.githubusercontent.com/assets/498744/7150845/c0521782-e2ee-11e4-9a7a-8584aa97e1e6.png)

I'm running python 2.7.9 and `ipython notebook --version` is 3.0.0. One weird thing is that my header looks different from what's in the readme and under kernal it says `Python 2`

![screen shot 2015-04-14 at 21 40 37 pm](https://cloud.githubusercontent.com/assets/498744/7150852/f36d281e-e2ee-11e4-96e6-4408466eb136.png)
![screen shot 2015-04-14 at 21 40 46 pm](https://cloud.githubusercontent.com/assets/498744/7150851/ef68784a-e2ee-11e4-81eb-8bd1a20caa5f.png)

**Comment by n-riesco** [comment]
It looks like you may be running the `npm` package rather than the latest github version. If you want to install the latest github commit, you can do so by running:

```sh
git clone https://github.com/n-riesco/ijavascript.git
sudo npm install -g ./ijavascript
```

I need to update the documentation before publishing the new release in the `npm` repository. I reckon I will do so some time this week.

**Comment by n-riesco** [comment]
Hi! Just to let you know that I've already published the new release in the `npm` repository.

I've also updated the documentation and added a few examples showing how to output HTML, SVG, PNG and JPEG content. See [doc/graphics.md](https://github.com/n-riesco/ijavascript/blob/master/doc/graphics.md).

**Comment by mhkeller** [comment]
Sorry for the delay. This works great! I had checked the version number between GitHub and Npm but foolishly didn't test the package as I had done before. 

I'm going to start playing around with this more. Very neat!

**Comment by thwee-alchemist** [comment]
Is it possible to create a canvas element via $$html$$? I tried the following code, but to no avail:
```

var THREE = require('three');
var width = 500;
var height = 300;

$$html$$ = `<canvas width="${width}" height="${height}"></canvas>`;

var scene = new THREE.Scene();
var camera = new THREE.PerspectiveCamera(75, width/height, 0.1, 1000 );

var renderer = new THREE.WebGLRenderer({canvas: $$html$$});
renderer.setSize(width, height);

var geometry = new THREE.BoxGeometry( 1, 1, 1 );
var material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
var cube = new THREE.Mesh( geometry, material );
scene.add( cube );

camera.position.z = 5;

var animate = function () {
  requestAnimationFrame( animate );

  cube.rotation.x += 0.1;
  cube.rotation.y += 0.1;

  renderer.render( scene, camera );
};

animate();
```
The canvas element shows up in my notebook, but nothing is rendered in it.

**Comment by n-riesco** [comment]
@thwee-alchemist What does `THREE.WebGLRenderer` expect to get as `canvas`?

**Comment by n-riesco** [comment]
@thwee-alchemist could you open a new issue, please?
