### ISSUE TITLE
Tweak to installation documentation

### ISSUE THREAD

**Issue by jonathaneunice** [n-riesco/ijavascript#91]
Just installed ijavascript. Running great. The install process, however, was not rapid or smooth. Would like to accelerate others' install efforts.

**Problem** On macOS (note: it's no longer called "OS X") I have Jupyter running for Python. Did `npm i -g ijavascript`. Seemed to install fine, but no joy. Running Jupyter  (`jupyter notebook`) showed no JS kernel installed. There seemed to be no clear info on how to add ijavascript's Jupyter `kernelspec`. Dug around for many minutes. Finally noticed the `ijs` command mentioned. Tried it, worked great. Better yet, it installed the kernelspec. Now all subsequent Jupyter invocations are savvy to the JS kernel. Would like install instructions to be explicit about need to run `ijs` at least once, not just use normal Jupyter commands.

If you agree, happy to submit related pull request.

**Comment by n-riesco** [comment]
Thank you for the feedback. It does help me understand how users expect IJavascript to work.

And yes, I'm happy for you to submit a PR.

**Comment by rgbkrk** [comment]
Same here, I still find it odd I have to run `ijs` which is why I went the `ijs-kernel` route to make setting up the kernelspec easier. With the `ijs` setup, for me to get someone started in nteract or Hydrogen I have to tell them to:

0. Install Jupyter
1. `npm install ijs`
2. run `ijs`
3. close the tab for jupyter notebook
4. stop the server
5. kernel is now installed

**Comment by n-riesco** [comment]
Here goes a little bit on the history of `ijs`.

At the time IJavascript was first released, `ijs` was a simple wrapper around `ipython notebook` and thus it accepts all the flags `ipython notebook` accepts. Note that at that time (the time of profiles) the dashboard would only be able to launch one type of kernel. Later came Jupyter and the time of kernel specs. And to address the need for kernel specs, `ijs` added the flag `--ijs-install=[local|global]` (see [usage](http://n-riesco.github.io/ijavascript/doc/usage.md.html)).

This issue and Kyle's comment makes me think that I need to move the section on installing kernel specs to the main `README.md` and make the link to the usage documentation more visible.
