### ISSUE TITLE
How to disable 'undefined' output

### ISSUE THREAD

**Issue by thisroot** [n-riesco/ijavascript#96]
Hi, wonderful library, but it is very annoying 'undefined' output, is it possible to remove its?

**Comment by n-riesco** [comment]
There is a command flag for that: `--ijs-hide-undefined`. To get a list of all the IJavascript flags, run: `ijs --ijs-help`.

**Comment by thisroot** [comment]
Thanks!

**Comment by thisroot** [comment]
How it's use from jupyter notebook?

**Comment by n-riesco** [comment]
@thisroot Did you try to run `ijs --ijs-hide-undefined`?

**Comment by rgbkrk** [comment]
@n-riesco it sounds like the question is how to configure the `kernel.json` to have this option so it comes up from the same notebook server as people use for Python.

**Comment by n-riesco** [comment]
@thisroot @rgbkrk

I'm using something like this to test [Hydrogen](https://github.com/nteract/hydrogen):

```
"kernelspecs": {
    "ijavascript": {
        "spec": {
            "display_name": "IJavascript",
            "env": {},
            "argv": [
                "ijskernel",
                "--hide-undefined",
                "--protocol=5.0",
                "{connection_file}"
            ],
            "language": "javascript"
        },
        "resources_dir": "/home/user/lib/node_modules/ijavascript/images"
    }
}
```

**Comment by rgbkrk** [comment]
@thisroot run `jupyter kernelspec list`. You'll see output like:

```
  javascript      /Users/kylek/Library/Jupyter/kernels/javascript
```

Edit `/Users/kylek/Library/Jupyter/kernels/javascript/kernel.json` (append `kernel.json` to the path above for the javascript entry).

```json
{
  "argv": [
    "ijskernel",
    "--hide-undefined",
    "{connection_file}",
    "--protocol=5.0"
  ],
  "display_name": "Javascript (Node.js)",
  "language": "javascript"
}
```

For what it's worth, I prefer hiding undefined by default as well.

**Comment by n-riesco** [comment]
@rgbkrk There shouldn't be any need for editing the kernel spec. This should happen automatically when you run `ijs --ijs-hide-undefined`.

There are several open issues that have highlighted that the original purpose of `ijs` as a wrapper around `jupyter notebook` is dated and confusing.

To address this confusion and acknowledge the three main use-cases of IJavascript, I'm planning to introduce the commands `ijsinstall`, `ijsconsole` and `ijsnotebook`.
