### ISSUE TITLE
Ijs startup command doesn't works

### ISSUE THREAD

**Issue by tesseslol** [n-riesco/ijavascript#98]
ijs
Error running `jupyter kernelspec install --replace C:\Users\TESSAR~1\AppData\Local\Temp\55c10d7325f3036cc71ab1489f2feeca\javascript --user`
Error: Command failed: jupyter kernelspec install --replace C:\Users\TESSAR~1\AppData\Local\Temp\55c10d7325f3036cc71ab1489f2feeca\javascript --user
Traceback (most recent call last):
  File "d:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python36\Scripts\jupyter.exe\__main__.py", line 9, in <module>
  File "C:\Users\Tessari Davide\Anaconda3\Lib\site-packages\jupyter_core\command.py", line 186, in main
    _execvp(command, sys.argv[1:])
  File "C:\Users\Tessari Davide\Anaconda3\Lib\site-packages\jupyter_core\command.py", line 104, in _execvp
    raise OSError('%r not found' % cmd, errno.ENOENT)
OSError: [Errno 'jupyter-kernelspec' not found] 2

Traceback (most recent call last):
  File "d:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python36\Scripts\jupyter.exe\__main__.py", line 9, in <module>
  File "C:\Users\Tessari Davide\Anaconda3\Lib\site-packages\jupyter_core\command.py", line 186, in main
    _execvp(command, sys.argv[1:])
  File "C:\Users\Tessari Davide\Anaconda3\Lib\site-packages\jupyter_core\command.py", line 104, in _execvp
    raise OSError('%r not found' % cmd, errno.ENOENT)
OSError: [Errno 'jupyter-kernelspec' not found] 2

but with jupyter-kernelspec work

**Comment by n-riesco** [comment]
@tesseslol Judging by the log, it looks like there are two installations of Python on your computer:
- one provided by anaconda and installed on the C: drive,
- and the other installed on the D: drive

**Comment by tesseslol** [comment]
\AppData\Roaming\npm\node_modules\ijavascript\bin\ijavascript.js:310
                context.version.frontend
                               ^

TypeError: Cannot read property 'frontend' of undefined
    at C:\Users\Tessari Davide\AppData\Roaming\npm\node_modules\ijavascript\bin\ijavascript.js:310:32
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by n-riesco** [comment]
@tesseslol Thanks for that log. I'll fix the error message. But note that fixing the error message won't fix the issue in your computer.

**Comment by n-riesco** [comment]
I've fixed the error messages in master. To install IJavascript from master, run:

```sh
npm install -g git+https://github.com/n-riesco/ijavascript.git
```

**Comment by tesseslol** [comment]
Error parsing Jupyter version:

**Comment by n-riesco** [comment]
@tesseslol  What do you get when you run `jupyter --version`?

**Comment by tesseslol** [comment]
@n-riesco https://i.imgur.com/sof4n0e.png

**Comment by tesseslol** [comment]
@n-riesco  When i lunch this command an instance of atom is opening. I think there is some problems with hydrogen package for atom.

Video: https://youtu.be/wcGeAKE-yeM

**Comment by n-riesco** [comment]
@tesseslol I still suspect there is a problem with the installation of jupyter. Could you run the following in a Python console?

```
In [1]: from jupyter_core.version import __version__

In [2]: __version__
Out[2]: '4.3.0'
```

**Comment by n-riesco** [comment]
Also, running the following in the Windows prompt may give us more info:

```
C:\> where jupyter
```

**Comment by tesseslol** [comment]
1° command:
    
    C:\Users\Tessari Davide>python
    Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from jupyter_core.version import __version__
    >>> __version__
    ' 4.2.1'
    
2° command:

    C:\Users\Tessari Davide>where jupyter
    C:\Users\Tessari Davide\Anaconda3\Lib\site-packages\jupyter.py
    C:\Users\Tessari Davide\Anaconda3\Scripts\jupyter.exe

**Comment by n-riesco** [comment]
I've just watched the video. It looks like your machine is configured to open python files using Atom. I'm not sure why that happens when you run `jupyter` from the command line.

Are you affected by [this issue](http://stackoverflow.com/a/42047557)?

**Comment by n-riesco** [comment]
Does the following work?

```
"C:\Users\Tessari Davide\Anaconda3\Scripts\jupyter.exe" --version
```

**Comment by tesseslol** [comment]
@n-riesco yes work

**Comment by n-riesco** [comment]
Not sure it'll work, but you could try to define a macro before running `ijs`. Like this:

```
doskey jupyter=jupyter.exe $*
```

But this is really just a quick patch. The underlying issue is that `jupyter.py` is open by Atom, instead of run by `python.exe`.

**Comment by tesseslol** [comment]
Work !!! thz

**Comment by josephtan** [comment]
Hi all,

I'm having similar issue when running "ijsinstall" or "ijs", and does anyone here know how to edit the cmd file for the command to execute as "jupyter-kernelspec" instead of "jupyter kernelspec" ?

> D:\Anaconda>ijs
Error running `jupyter kernelspec install --replace C:\Users\xxx\AppData\Lo
cal\Temp\7fc7c6641f9defe1d7cb4db35bc82cb5\javascript --user`
Error: Command failed: jupyter kernelspec install --replace C:\Users\xxx\Ap
pData\Local\Temp\7fc7c6641f9defe1d7cb4db35bc82cb5\javascript --user
Error executing Jupyter command 'kernelspec': [Errno 'jupyter-kernelspec' not fo
und] 2
